### ISSUE TITLE
Add support for custom options.

### ISSUE THREAD

**Issue by victorr** [protobufjs/protobuf.js#10]
This is a request to add support for custom options. See "Custom options" in [Protocol Buffers Language Guide](https://developers.google.com/protocol-buffers/docs/proto#options).

I have attempted to create unit tests. I'll submit a pull request.

Thank you in advance!

**Comment by anchel** [comment]
> At work we have built an RPC framework on top of protocol buffers. Custom options are used to identify what protocols messages belong to, etc.
> 
> I'm hoping to use ProtoBuf.js to demonstrate that javascript is a viable choice for writing clients and servers for the framework.

i have the same case, how you resolve ?
