### ISSUE TITLE
Serialization in binary wire format for protocol buffer messages

### ISSUE THREAD

**Issue by grandkarabas** [protobufjs/protobuf.js#1032]
protobuf.js version: 6.8.6

Does __protobuf.js__ support message serialization method in [binary wire format for protocol buffer messages](https://developers.google.com/protocol-buffers/docs/encoding)? Currently I did not find any solution for this. 

I have a pythonic backend and javascript frontend. They both use one common _.proto_ file. I want to parse messages at backend from frontend in the following manner ([FromString example](https://developers.google.com/protocol-buffers/docs/reference/python-generated)):
```py
MyMessage message;
parsed = message.FromString(s);
```
Thanks in advance.

**Comment by alexander-fenster** [comment]
It does: use `encode` method of your `MyMessage` class.

```js
const buffer = MyMessage.encode(message).finish();
```

To deserialize a message from a buffer, use `decode`.
