### ISSUE TITLE
Cannot find name 'Long'

### ISSUE THREAD

**Issue by b1naryMan** [protobufjs/protobuf.js#1071]
protobuf.js version: 6.8.4

After generating code using pbjs and pbjs:

node_modules/protobufjs/bin/pbjs --force-long -t static-module -w  commonjs -o info.protobuf.js info.proto
node_modules/protobufjs/bin/pbts -o info.d.ts info.protobuf.js

I have included the long and @types/long in my package.json file:
	"long": "^4.0.0",
	"@types/long": "^4.0.0",

In my tsconfig.json file I have the following:
``
{
  "compileOnSave": false,
  "compilerOptions": {
   ...
   "types": [
      "node_modules/long"
    ],
    "typeRoots": [
      "node_modules/@types",
    ]
  },
  "include": [
    "src/**/*",
    "src/assets/proto/*.d.ts"
  ],
  "files": [
     ...
  ]
}
``

I import the generated typescript file in my component but when I try to compile I get the following error in
	info.d.ts: Cannot find name 'Long'

How can I resolve this issue?
Thanks in advance

**Comment by chloe2018s** [comment]
hi did you resolve this issue eventually ? got the same issue here. thx

**Comment by JustinBeckwith** [comment]
Greetings!  I'm pretty sure we fixed this over in #1166. We will look into cutting a release next!

**Comment by esilkensen** [comment]
Hi @JustinBeckwith, thanks for the fix! Do you know when this might make it into a release?
