### ISSUE TITLE
Potential issue with serialization of default values

### ISSUE THREAD

**Issue by cjihrig** [protobufjs/protobuf.js#1118]
protobuf.js version: protobufjs@6.8.8 via @grpc/proto-loader@0.3.0

According to https://developers.google.com/protocol-buffers/docs/proto3#default, default values should not be serialized:

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

However, I am observing default values being serialized.

**Reproduction:**
test.proto:
```
syntax = "proto3";

package test;

service Test {
    rpc Tester (TestRequest) returns (TestResponse) {
    }
}

message TestRequest {
    string str = 1;
    bool boolean = 2;
}

message TestResponse {
}
```

```js
'use strict';
const protobuf = require('protobufjs');

protobuf.load('test.proto', (err, root) => {
  if (err) {
    throw err;
  }

  const TestRequest = root.lookupType('test.TestRequest');

  console.log(TestRequest.encode({ str: 'test', boolean: true }).finish());
  // <Buffer 0a 04 74 65 73 74 10 01>
  console.log(TestRequest.encode({ str: 'test', boolean: false }).finish());
  // <Buffer 0a 04 74 65 73 74 10 00>
  console.log(TestRequest.encode({ str: 'test' }).finish());
  // <Buffer 0a 04 74 65 73 74>
});
```

Since `false` is the default Boolean value, I would expect the second and third `Buffer`s to be the same size. Instead, the first and second `Buffer`s are the same size because the default value is serialized.

Refs: https://github.com/grpc/grpc-node/issues/566

**Comment by dlang123** [comment]
I am having this issue as well.  We are sending encoded packets over the wire with CRC values attached, and this causes our two application CRC's to differ.  Took me a while to track this bug down.  Any word on work arounds or possible fixes?

**Comment by acode-x** [comment]
@alexander-fenster @JustinBeckwith 
Is there any plan to fix this bug in future releases?
