### ISSUE TITLE
Is there any thing different from the standard protobuf?

### ISSUE THREAD

**Issue by jianjungki** [protobufjs/protobuf.js#112]
I use protobuf in php with
https://github.com/drslump/Protobuf-PHP

But i can't decode from the data which php save(I use the Protobuf-PHP default codec,it's binary)

![image](https://f.cloud.github.com/assets/1188643/2330755/fe3dda2e-a43b-11e3-95a9-72370b105d04.png)

then i use the ByteBuffer.wrap()
![image](https://f.cloud.github.com/assets/1188643/2330762/258c0452-a43c-11e3-8bf1-654c04ab66eb.png)

it's useless and i want to know whether there is something different from the standard.
I can decode from the binary which php save with C++

**Comment by venkatpathapati** [comment]
How to decode protobuf binary data with out knowing .proto file. I need help on how to identify different data type's especially wire type 2.
