### ISSUE TITLE
Counterpart to writeDelimitedTo/parseDelimitedFrom

### ISSUE THREAD

**Issue by sorccu** [protobufjs/protobuf.js#115]
I often find myself missing the built-in [parseDelimitedFrom](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/AbstractParser#parseDelimitedFrom%28java.io.InputStream%29) and [writeDelimitedTo](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageLite#writeDelimitedTo%28java.io.OutputStream%29) from the official Java API.

You can kind of replicate the functionality with this:

``` javascript
var ByteBuffer = require('protobufjs/node_modules/bytebuffer')

var lengthBuffer = new ByteBuffer()
var messageBuffer = new SomeMessage(muchData).encodeNB()

// Delimiter
lengthBuffer.writeVarint32(messageBuffer.length)

socket.write(lengthBuffer.toBuffer())
socket.write(messageBuffer)
```

... but it's obviously a bit of a pain. Now I know that for example the C++ API doesn't have these methods either, but then again it's C++, where few things are convenient.

I may have missed an easier method to achieve the same result (if so, please let me know), but it would be great if we could get some kind of an `encodeDelimited` and `decodeDelimited` methods for convenience. Or, it would at least be nice to have a one-liner to create the delimiter without having to require ByteBuffer.

**Comment by jfromaniello** [comment]
@dcodeIO Can you show me an example of this? I'm looking for a way to buffer an stream of a socket. It would be nice to have an api like this:

```
socket.pipe(ByteStream)
    .pipe(Message.decodeDelimited)
    .on(data, function (message) {
      console.log('do something with my message', message);
    });
```

**Comment by jfromaniello** [comment]
This is what I ended up doing

```javascript
var server = net.createServer(function (socket) {
  var buffer;

  socket.pipe(through(function (chunk) {
    chunk = ByteBuffer.wrap(chunk);
    buffer = buffer ? ByteBuffer.concat([buffer, chunk]) : chunk;

    var decoded;

    while (buffer.remaining() > 0 && (decoded = Request.decodeDelimited(buffer))) {
      buffer.compact();
      this.queue(decoded);
    }

  })).on('data', function (m) {
    console.log(m);
  });

});
```

**Comment by kirillgroshkov** [comment]
Spent few hours looking for solution, and here's my working version:

```typescript
function transformFromProtobuf<OUT>(type: protobuf.Type): TransformTyped<Buffer, OUT> {
  let remainder = Buffer.alloc(0)

  return new Transform({
    objectMode: false,
    readableObjectMode: true,
    async transform(chunk: Buffer, _encoding, cb) {
      // console.log(chunk)
      const buf = Buffer.concat([remainder, chunk])

      let lastPos = 0
      const reader = protobuf.Reader.create(buf)
      try {
        while (reader.pos < reader.len) {
          lastPos = reader.pos
          const frame = type.decodeDelimited(reader)
          this.push(frame)
        }

        remainder = Buffer.alloc(0)
      } catch (err) {
        // console.log({pos: reader.pos, lastPos, len: reader.len}, 'got err')
        remainder = buf.slice(lastPos)
      }
      // console.log(`remainder size: ${remainder.length}`)
      cb() // finished processing
    },
  })
}

```
