### ISSUE TITLE
What tools are the pictures in readme made of?

### ISSUE THREAD

**Issue by zlq4863947** [protobufjs/protobuf.js#1173]
How is this picture below done, can someone tell me?
Thank you
![](https://camo.githubusercontent.com/f090df881cc6c82ecb7c5d09c9fad550fdfd153e/687474703a2f2f64636f64652e696f2f70726f746f6275662e6a732f746f6f6c7365742e737667)

**Comment by JustinBeckwith** [comment]
Greetings!  We're really not sure :) Guessing you could make that image with any image editor!

**Comment by dcodeIO** [comment]
It's www.draw.io I believe
