### ISSUE TITLE
Consider exposing missing common google protos

### ISSUE THREAD

**Issue by cjihrig** [protobufjs/protobuf.js#1180]
protobuf.js version: latest

protobufjs provides [some common Google types](https://github.com/dcodeIO/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/common.js#L12-L18), but [not others](https://github.com/dcodeIO/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/common.js#L34-L41). This is pretty confusing behavior, particularly if you've successfully used one, but run into 'unresolvable extensions' errors on another. This is easy enough to work around once you've figured out what's going on, but it's not immediately obvious.

I'm willing to submit a PR for this.

**Comment by xblv** [comment]
hi there, meet the same problem here. At least in our project, we need to support `google/protobuf/descriptor.proto` into common.
Thanks and any update for this issue?

**Comment by cjihrig** [comment]
@JustinBeckwith any thoughts on this? It would allow https://github.com/grpc/grpc-node/commit/cbff0b46012ce286e1b54c7a05128667b0d72aad#diff-a475274003c9fd63e21d85b6ec3c7cfa to be partially reverted - assuming the test would not be reverted. It would also keep the loading of well-known protos in one place instead of split across the two projects.

**Comment by dcodeIO** [comment]
Initial reasons for not bundling descriptor.proto were its sheer size and that protobuf.js itself doesn't need it to function, so loading it on demand seems appropriate. That's why the `common` functionality is exposed, and to me the commit above appears to do it just as intended.
