### ISSUE TITLE
Using pbjs gets a empty file

### ISSUE THREAD

**Issue by LL-LAILAI** [protobufjs/protobuf.js#1193]
protobuf.js version: ^6.8.8

I want to use Command line to to bundle my .proto files to a single .json file. But the .json file is a Empty file. And the prompt 'pbjs' is not an internal or external command, nor a runnable program or batch file.

```js
pbjs -t json message.proto > bundle.json

```

```
pbjs -t json message.proto > bundle.json
```

**Comment by JustinBeckwith** [comment]
Greetings!  How are you running `pbjs`?  You either need to use `npx`:

```sh
$ npx pbjs -t json message.proto > bundle.json
```

Or, you would need to run this as an npm script:

```sh
$ cat package.json

{
  "name": "ttt",
  "scripts": {
    "gen": "pbjs -t json message.proto > bundle.json"
  },
  "dependencies": {
    "protobufjs": "^6.8.8"
  }
}

$ npm run gen
```

Please try one of these two methods, and let us know if you're still having issues!
