### ISSUE TITLE
Maintenance of protobufjs

### ISSUE THREAD

**Issue by hsaliak** [protobufjs/protobuf.js#1199]
@dcodeIO is the project maintained? As you know, we ( grpc-node team) have protobufJS as a dependency. 
If you need some extra hands maintaining the repo and reviewing, we would be happy to help.

**Comment by cjihrig** [comment]
As a grpc-node user, and Node core team member, I'd just like to add that Node has a package-maintenance team that is looking to help maintain modules from the ecosystem that are heavily relied on. I think protobufjs falls into that category, and I'd be happy to connect you with that group if that's desirable.

**Comment by dcodeIO** [comment]
For a bit of background: A while ago I started a new project named AssemblyScript, a TypeScript to WebAsembly compiler, which turned out to be financially supported by interested parties. So my focus since shifted. Not because I wouldn't love protobuf.js, but because I also need to survive somehow to be still around to maintain anything in the first place. I still expect to gravitate back to protobuf.js every once in a while when larger stuff is due, but on my own terms, because I have to.

So, yes, I am open to add additional maintainers from a trusted team relying on protobuf.js. GRPC seems like the best fit.

**Comment by dcodeIO** [comment]
As a first step I've moved the repository and its (deprecated) hard dependencies to a new organization [protobufjs](https://github.com/protobufjs) and invited @hsaliak.

**Comment by hsaliak** [comment]
Unfortunately I am one of the more manegerial types.. could you please invite @nicolasnoble and @murgatroid99

**Comment by nicolasnoble** [comment]
@hsaliak: you technically can do it yourself now :-)

**Comment by dcodeIO** [comment]
Alright, done. You guys should have write access to the repositories now so you can merge PRs, make commits etc. Please let me know if you need anything else or have further questions :).

Can also imagine that setting up automated npm releases based on Git tags would simplify the release process in the long run. Wdyt?

**Comment by nicolasnoble** [comment]
That'd be fine with me, yes.

**Comment by nicolasnoble** [comment]
So @dcodeIO, there's quite a few more people here at the Google office who can help, and not just myself or @murgatroid99. We in fact have a slew of hands who can help. Would you mind bumping my rights so I can also start building the team, add more people, assign roles, etc?

**Comment by dcodeIO** [comment]
Sure, created a team for you guys and added you as its maintainer. Let me know if this works for you :)

**Comment by nicolasnoble** [comment]
Unfortunately, it doesn't seem to be quite enough for me to fully add people: ![image](https://user-images.githubusercontent.com/7281574/56377772-019a1100-61c0-11e9-83cf-afdac6321f2f.png)

**Comment by dcodeIO** [comment]
I see, seems this doesn't work with teams alone then. You should have full access to the org now :)

**Comment by JustinBeckwith** [comment]
Thank you so much @dcodeIO and @nicolasnoble for getting this worked out :) It looks like we have some additional hands to help in here, so I'm going to close this one out!

**Comment by eyalpost** [comment]
Has the project gone on hiatus again? It doesn't seem like there was any activity from the maintainers in quite some time

**Comment by glasser** [comment]
Is this project open to new maintainers? We rely on protobufjs and have some improvements we'd like to make (including one PR that hasn't gotten any response in a few months). We are working on forking protobufjs for our own use, but would be happy to help maintain the actual project as well.

**Comment by darioAnongba** [comment]
@glasser Did you manage to fork the project or get some news about maintenance?

**Comment by glasser** [comment]
We have a fork for our own use at https://www.npmjs.com/package/@apollo/protobufjs
We don't necessarily want to maintain that as a general-use package though.
