### ISSUE TITLE
API documentation website 404

### ISSUE THREAD

**Issue by kaiwk** [protobufjs/protobuf.js#1210]
It seems one can't access this website:

https://dcode.io/protobuf.js

**Comment by dcodeIO** [comment]
Ah, right, that changed when moving the repo to its own org. New link is: https://protobufjs.github.io/protobuf.js/

**Comment by kaiwk** [comment]
I found the link in the wiki page. Thanks, problem solved.

**Comment by T3sT3ro** [comment]
the wiki link for API documentation V6 point to 404: https://github.com/protobufjs/protobuf.js/wiki  
so does the link on https://www.npmjs.com/package/protobufjs#additional-documentation
