### ISSUE TITLE
pbts 6.8.8 with jsdoc 3.6 is generating incorrect descriptor files

### ISSUE THREAD

**Issue by mdouglass** [protobufjs/protobuf.js#1217]
protobuf.js version: 6.8.8

pjts is generating files with missing interfaces likely because of this upstream issue https://github.com/jsdoc/jsdoc/issues/1644.
Would it be possible to pin to jsdoc@3.5 for the time being?

**Comment by springhack** [comment]
I made a simple script to generate *.d.ts, to solve this problem for my usage
https://gist.github.com/springhack/f69a7e9bd27e40e5fbf2dc6d6cffd65e
