### ISSUE TITLE
util.isNode / Error: not supported

### ISSUE THREAD

**Issue by jumpinvestor** [protobufjs/protobuf.js#1221]
protobuf.js version: 6.8.8
Ubuntu: 19.04
Node: 12.2.0
Angular: 7.2.15 with server-side rendering enabled

I'm seeing "Error: not supported" popping up in an Angular 7 app on Node 12.2.0. Just upgraded Node from 10.15.3, where it did not have the error.

<img width="1086" alt="Screen Shot 2019-05-13 at 3 35 06 PM" src="https://user-images.githubusercontent.com/14829156/57658795-fe166180-7594-11e9-81f4-e64d352ce27c.png">

After a little digging, it looks like this references _/src/root.js_:233-234:

<img width="966" alt="Screen Shot 2019-05-13 at 3 50 00 PM" src="https://user-images.githubusercontent.com/14829156/57659329-d32d0d00-7596-11e9-9349-36a128b363c2.png">

and _/src/util/minimal.js_:55:

<img width="968" alt="Screen Shot 2019-05-13 at 3 38 05 PM" src="https://user-images.githubusercontent.com/14829156/57659002-96144b00-7595-11e9-8644-9ecf1686eab5.png">

After commenting out the check in root.js, everything seems to work fine. Is there another solution?

**Comment by dcodeIO** [comment]
The check is here: https://github.com/protobufjs/protobuf.js/blob/master/src/util/minimal.js#L55

There might be something in your stack invalidating it, or did node change something?

**Comment by jumpinvestor** [comment]
I think it might be related to Angular's server-side rendering. The util object captures global.document but not global.process, which could make sense for SSR:

<img width="463" alt="Screen Shot 2019-05-14 at 8 23 34 AM" src="https://user-images.githubusercontent.com/14829156/57710490-e46f2b80-7621-11e9-935a-b783fe28326b.png">

**Comment by MichaelSolati** [comment]
I'm having a similar, so what I found worked (which I don't think would be a hard/serious change) is in `src/util/minimal.js` I reordered the `util.global`. It was:

```JavaScript
util.global = typeof global !== "undefined" && global
           || typeof window !== "undefined" && window
           || typeof self   !== "undefined" && self
           || this; // eslint-disable-line no-invalid-this
```

And I swapped it to this:

```JavaScript
util.global = typeof global !== "undefined" && global
           || typeof window !== "undefined" && window
           || typeof self   !== "undefined" && self
           || this; // eslint-disable-line no-invalid-this
```

I'm using mocha with jsdom so the window object is passing first and therefore being set as the global, not the NodeJS.Global! But if I swap the order it works fine. Could this be implemented into the regular library?

**Comment by dcodeIO** [comment]
Hmm, good question. The old order assumes that a global `window` is super unlikely inside of a node module because there isn't an implicit global scope one could accidentally declare such a variable in, while the new depends on the assumption that no dev would ever define a global var named `global` in a browser context, which is unlikely.

**Comment by mfursov** [comment]
I believe this may be a conflict with NestJS people use a lot for SSR:
https://github.com/nestjs/ng-universal/blob/master/lib/utils/domino.utils.ts

If protobuf.js is initialized first, there is no error with isNode mode detection.

**Comment by jumpinvestor** [comment]
That makes sense.

**Comment by MichaelSolati** [comment]
It's also an issue if you are using `jsdom` with `mocha`.

**Comment by Iar0** [comment]
same, I had this with the latest version of firebase (currently 6.4.0). I needed to downgrade to "^5.9.1" to still have SSR working.

There are some valid comments up in the thread: what's the best way to approach this?

**Comment by diegoblattner** [comment]
Several questions arise from this...
```
util.isNode = Boolean(process && process.versions && process.versions.node);
```
Fixes the problem, considering process is a global variable since node [0.1.7](https://nodejs.org/api/globals.html#globals_process) and `versions` since [0.2.0](https://nodejs.org/api/process.html#process_process_versions)
I will create a PR.
