### ISSUE TITLE
--es6 in combination with --wrap commonjs not possible

### ISSUE THREAD

**Issue by renkei** [protobufjs/protobuf.js#1308]
protobuf.js version: 6.8.8

I want to use --es6 flag for pbjs in order to get const/let instead of var. But I still want to use commonjs instead of the new ECMAScript modules.

If I set the --es6 flag then --wrap is automatically set to es6 as well. As far as I understand it should be the other way around. If I enable --wrap es6 then --es6 should be also enabled.

I checked the code of pbjs.js and removed `|| argv.es6` in line 198. Now it seems to work, I get const/let instead of var but still `require('...')` instead of `import * as ... from ...`

```js
// pbjs.js, original code from protobufjs 6.8.8
//
// Use es6 syntax if not explicitly specified on the command line and the es6 wrapper is used
if (argv.wrap === "es6" || argv.es6) {
    argv.wrap = "es6";
    argv.es6 = true;
}

// pbjs.js, modified code
//
// Use es6 syntax if not explicitly specified on the command line and the es6 wrapper is used
if (argv.wrap === "es6") {
    argv.es6 = true;
}

```

**Comment by webmaster128** [comment]
I created a PR fixing this: #1430. Tested it locally and it works.
