### ISSUE TITLE
Setting the default value to a string field causes a bad result

### ISSUE THREAD

**Issue by toshirin33** [protobufjs/protobuf.js#1357]
protobuf.js version: +-- protobufjs@6.8.8

When the default value for string, empty string represented by '' or "" is set to a string field,
the serialized result is different from the one the value is not set.

tmp.protoc
```
syntax = "proto3";
package protobuf;

message tuple {
  string f1 = 1;
  string f2 = 2;
}
```

poi.js
```
let protobuf = require('protobufjs');

function output_pb(tuple, payload){
    let errMsg = tuple.verify(payload);
    if (errMsg)
        throw Error(errMsg)

    let obj = tuple.create(payload);

    let buf = tuple.encode(obj).finish();

    console.log(buf.toString("hex"));
}

protobuf.load("tmp.proto", function(err, root){
    let tuple = root.lookupType("protobuf.tuple");

    let payload = {f1: "hello"};
    output_pb(tuple, payload);

    payload = {f1: "hello", f2:""};
    output_pb(tuple, payload);
    
})
```

Output is the following
```
$ node poi.js
0a0568656c6c6f
0a0568656c6c6f1200
```

**Comment by toshirin33** [comment]
The result was valid . I have noticed that the encoded values give the same decoded value.
I thought the serialized value is unique but it is not true.

**Comment by toshirin33** [comment]
In https://developers.google.com/protocol-buffers/docs/proto3#default I found the following sentence.

> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

I think the result 0a0568656c6c6f1200 should be 0a0568656c6c6f .

**Comment by webmaster128** [comment]
Thank you for pointing this out. I agree this is a bug in the encoder. The same problem exist at least for numbers as well.

**Comment by webmaster128** [comment]
This is pretty much a duplicate of #1118 (just for string instead of bool)

**Comment by toshirin33** [comment]
Thank you for showing #1118.  I agree that this issue is a duplicate of that, so I close this issue.
