### ISSUE TITLE
Decoding int64 gives object instead of value

### ISSUE THREAD

**Issue by eamonnmcevoy** [protobufjs/protobuf.js#1379]
When I decode a buffer, all my int64 fields have the following structure:

decodedMessage.Id :
```
{ low: 20842, // this is the expected value
  high: 0,
  unsigned: false }
```

code:
```
const definitions = protobufjs.loadSync(`${__dirname}/../../protos/my-proto.proto`);
const type = definitions.lookupType('my-type');
const decodedMessage = type.decode(buffer);
```

Whats going on here, is this the expected behaviour?

**Comment by eamonnmcevoy** [comment]
I guess its caused by long.js, i need to manually call toString on each of my int64 values. e.g. `decodedMessage.Id.toString()`.

Shouldn't protobufjs do this automatically, Its a bit confusing ?

**Comment by brycefisher** [comment]
I agree! Please consider tackling this....
