### ISSUE TITLE
【Feature】enum type allow encode as a string

### ISSUE THREAD

**Issue by Gcaufy** [protobufjs/protobuf.js#1398]
When there is a enum field in a message. when we want encode it from a JSON, then enum field should be a number.
When we decode a buffer to a message, and then use `toObject` to transform it to a JSON object, we have an option which allow us to decide the enum is a number or a string.

If we decide to use output enum as a string, currently there is no way to encode it from the output directly.
So I hope we can support enum string when we encode from a JSON object.

Demo code:

```
// awesomepackage.proto
package awesomepackage;
syntax = "proto3";

enum Status {
  Active = 0;
  InActive = 1;
}
message AwesomeMessage {
    optional string text = 1;
    optional Status status = 2; 
}
```

```
// test.js
const protobuf = require('protobufjs');

protobuf.load('./awesomepackage.proto', function (err, root) {
  const AwesomeMessage = root.lookupType('awesomepackage.AwesomeMessage');

  
  const buffer1 = AwesomeMessage.encode({ text: 'hello', status: 1 }).finish();
  const decode1 = AwesomeMessage.decode(buffer1);
  const json = AwesomeMessage.toObject(decode1, { enums: String });
  const buffer2 = AwesomeMessage.encode(json).finish();
  const decode2 = AwesomeMessage.decode(buffer2);

  console.log(decode1.status === decode2.status); // false. becuase encode do not support string enum.

})
```

Expect:
```
AwesomeMessage.encode({ text: 'hello', status: 1 }).finish();

// Generate the same buffer as above
AwesomeMessage.encode({ text: 'hello', status: 'InActive' }).finish();
```

When I checked the source code.
`encode` function is generated like this:

```
return function AwesomeMessage$encode(m,w){
  if(!w)
  w=Writer.create()
  if(m.text!=null&&Object.hasOwnProperty.call(m,"text"))
  w.uint32(10).string(m.text)
  if(m.status!=null&&Object.hasOwnProperty.call(m,"status"))
  w.uint32(16).int32(m.status)
  return w
}
```

Which is from here:

https://github.com/protobufjs/protobuf.js/blob/4ecfbcedaa4a9a85b9e896f38608519643390db4/src/encoder.js#L92

And we can get the enum keys here.
So I think we changed the generated code to:

```
return function AwesomeMessage$encode(m,w){
  if(!w)
  w=Writer.create()
  if(m.text!=null&&Object.hasOwnProperty.call(m,"text"))
  w.uint32(10).string(m.text)
  if(m.status!=null&&Object.hasOwnProperty.call(m,"status"))
  if (typeof m.status === 'string') {
    w.uint32(16).int32(({ "Active": 0, "InActive": 1})[m.status])
  } else {
    w.uint32(16).int32(m.status)
  }
  
  return w
}
```

This will support encode string enum.

If this feature looks good for you. then I can help to make a pull request to implement it.

**Comment by dcodeIO** [comment]
The intended mechanism to convert an arbitrary object, i.e. as created via `toObject` using its various options, back to a [valid message](https://github.com/protobufjs/protobuf.js#valid-message) is `fromObject`:

```js
const obj = AwesomeMessage.toObject(decode1, { enums: String });
const msg = AwesomeMessage.fromObject(obj);
...
```

Doesn't this work?

**Comment by Gcaufy** [comment]
Actually I'm using this code rpc service code.
So here is encode. 

https://github.com/protobufjs/protobuf.js/blob/master/src/rpc/service.js#L96

unless if you want to change encode to fromObject here.

**Comment by Gcaufy** [comment]
https://github.com/protobufjs/protobuf.js/blob/master/src/rpc/service.js#L96

See here.

If you want to add fromObject here, it will also fix my problem.

Daniel Wirtz <notifications@github.com> 于2020年4月30日周四 下午3:09写道：

**Comment by Gcaufy** [comment]
I'm use the rpc service code.

See here:

https://github.com/protobufjs/protobuf.js/blob/master/src/rpc/service.js#L96

If you want to add fromObject here, it will also fix my problem.

Daniel Wirtz <notifications@github.com> 于2020年4月30日周四 下午3:09写道：

**Comment by dcodeIO** [comment]
I might be missing something here, but protobuf.js does not call `fromObject` on every encode step intentionally to reduce overhead, and leaves it up to the user to do this where necessary. So, in the case of `rpcCall`, one would ensure that the `request` argument is a valid message upfront, so the library does not have to.

**Comment by Gcaufy** [comment]
[image: image.png]

Here is an example from your README.

When you are using a rpc service to do a rpcCall like this:
`greeter.sayHello`
The params is should be a JSON Object.  greeter.sayHello({ name: 'you' })
If you are doing greeter.sayHello(HelloRequest.fromObject({ name: 'you' }),
it will be good.
But the point is when you are doing a rpc call. you do not know the
RequestMessageType.  you only got the method, and a json params. so you are
not be able to call `fromObject`


In this case, if you want use fromObject, you should write the code like
this:

greeter.sayHello(greeter.methods.SayHello.resolvedRequestType.fromObject({
> name: 'you' }));



hope I can clarify the problem here.




Daniel Wirtz <notifications@github.com> 于2020年4月30日周四 下午5:34写道：

**Comment by Gcaufy** [comment]
Here is an example from your README.

![image](https://user-images.githubusercontent.com/2182004/80705975-0b1bc000-8b1a-11ea-8740-2def8f2f6f11.png)


When you are using a rpc service to do a rpcCall like this:  `greeter.sayHello`
The params is should be a JSON Object.  
```
greeter.sayHello({ name: 'you' })
```

It will be good. If you are doing 
```
greeter.sayHello(HelloRequest.fromObject({ name: 'you' })
```
But the point is when you are doing a rpc call. you do not know the RequestMessageType.  you only got the method, and a json params. so you are not be able to call `fromObject`


In this case, if you want use fromObject, you should write the code like this:

```
greeter.sayHello(greeter.methods.SayHello.resolvedRequestType.fromObject({ name: 'you' }));
```

hope I can clarify the problem here.

**Comment by Gcaufy** [comment]
Thanks for you time.
I totally understand in this issue, I should use toObject instead of encode.
So I will close this issue.

But for the rpc service call, It's nothing related to this one, so I will open another issue to discuss it.
