### ISSUE TITLE
Cannot read property 'fromJSON' of undefined while i used JEST for testing 

### ISSUE THREAD

**Issue by jabbar86** [protobufjs/protobuf.js#1409]
protobuf.js version: 6.8.8

when i run test cases using jest i get the below error

```
@grpc/proto-loader/node_modules/protobufjs/ext/descriptor/index.js (File)
"use strict";
var $protobuf = require("../..");
module.exports = exports = $protobuf.descriptor = $protobuf.Root.fromJSON(require("../../google/protobuf/descriptor.json")).lookup(".google.protobuf");

 ```
Test suite failed to run

    TypeError: Cannot read property 'fromJSON' of undefined

      at Object.<anonymous> (node_modules/@grpc/proto-loader/node_modules/protobufjs/ext/descriptor/index.js:3:66)
      at Object.<anonymous> (node_modules/@grpc/proto-loader/build/src/index.js:23:20)
```
@grpc/grpc-js : 0.7.4

@grpc/proto-loader : 0.5.1

Is this the issue in grpc module?

**Comment by jabbar86** [comment]
@dcodeIO

**Comment by dcodeIO** [comment]
Looks like `protobuf.Root` is not defined, but hard to tell what's causing it. Some details on ext/descriptor usage is here, in case it helps: https://github.com/protobufjs/protobuf.js/tree/master/ext/descriptor

**Comment by jabbar86** [comment]
yes when i console `protobuf.Root` it gives me undefined.What extran info you need so that i can provide you

**Comment by CNDW** [comment]
I was experiencing this issue as well, it turns out I had the following configuration
```
  moduleNameMapper: {
    'src/(.*)': '<rootDir>/src/$1',
    'test/(.*)': '<rootDir>/test/$1',
  },
```
this was remapping a requirement inside of the protobuf package to look for the module in my project instead of the package directory. Removing the module mapping configuration fixed the issue.

**Comment by jabbar86** [comment]
> I was experiencing this issue as well, it turns out I had the following configuration
> 
> ```
>   moduleNameMapper: {
>     'src/(.*)': '<rootDir>/src/$1',
>     'test/(.*)': '<rootDir>/test/$1',
>   },
> ```
> 
> this was remapping a requirement inside of the protobuf package to look for the module in my project instead of the package directory. Removing the module mapping configuration fixed the issue.

**Comment by jabbar86** [comment]
> I was experiencing this issue as well, it turns out I had the following configuration
> 
> ```
>   moduleNameMapper: {
>     'src/(.*)': '<rootDir>/src/$1',
>     'test/(.*)': '<rootDir>/test/$1',
>   },
> ```
> 
> this was remapping a requirement inside of the protobuf package to look for the module in my project instead of the package directory. Removing the module mapping configuration fixed the issue.

@CNDW works like a charm closing the issue.Feel free to reopen it.
