### ISSUE TITLE
protobuf.js 6.10.0 is incompatible with jest

### ISSUE THREAD

**Issue by starkwang** [protobufjs/protobuf.js#1443]
protobuf.js version: 6.10.0

# How to reproduce

See: https://github.com/starkwang/jest-protobufjs-incompatible

```js
const protobuf = require('protobufjs')

test('adds 1 + 2 to equal 3', (done) => {
    protobuf.loadSync("awesome.proto");
    expect(1 + 2).toBe(3);
});
```

# Reason

Jest has a mock `global` for each test. It is not a `[object global]` but a `[object Object]`

So the mock `global` will break the `util.global` in protobuf.js:

https://github.com/protobufjs/protobuf.js/blob/07e8185379d6ca6235b71685566c3ce4f594ed34/src/util/minimal.js#L29-L32

And `util.isNode` will return `false`:

https://github.com/protobufjs/protobuf.js/blob/07e8185379d6ca6235b71685566c3ce4f594ed34/src/util/minimal.js#L55

And then the `loadSync()` will throw an error:

https://github.com/protobufjs/protobuf.js/blob/07e8185379d6ca6235b71685566c3ce4f594ed34/src/root.js#L244-L248

**Comment by qazwsx9006** [comment]
+1

**Comment by seki2020** [comment]
+1

**Comment by alincode** [comment]
+1 

google pubsub depends on protobuf.js too, it will effect a lot project, I think. 😅

**Comment by amammay** [comment]
+1

**Comment by JonMontgo** [comment]
+1

**Comment by jhowr** [comment]
+1
