### ISSUE TITLE
protobuf in browser --  lookupType throw no such type: error

### ISSUE THREAD

**Issue by fordringd2008** [protobufjs/protobuf.js#1447]
protobuf.js version: <6.10.0>

<please describe the expected and actual behavior>

I use it in brower,  html, 

```js
<please provide a code snippet for reproduction>
My code is
<script src="./protobuf.js"></script>  // I download it to local

// My proto
package awesomepackage;
syntax = "proto3";

message AwesomeMessage {
    string awesome_field = 1; // becomes awesomeField
}

...
window.onload = ()=>{

            protobuf = window.protobuf;
            protobuf.load("./awesome.proto", function(err, root) {
                if (err) throw err;
                console.log('root:', root);
                var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");  // Here:  throw Error("no such type: " + path);
                console.log('AwesomeMessage:', AwesomeMessage);
            });
            // setupDrawView();
            // setupProto();
        };

**Comment by alexander-fenster** [comment]
Hi @fordringd2008,

Just to confirm: it's not a new problem that appeared in v6.10.0, right?

If I understand the problem correctly, `protobuf.load` uses Node.js `fs.readFileSync` to read the file from the filesystem, which won't work in browser. You can run `pbjs` to produce a JSON representation of your `awesome.proto`:

```sh
$ pbjs -t json -o awesome.json awesome.proto
```
and then pass the content of that JSON file to `protobuf.load`.

**Comment by fordringd2008** [comment]
@alexander-fenster 
I has tried your way, but the problem is still unsolved.

The converted json as follow:
// awesome.json

{
  "nested": {
    "awesomepackage": {
      "nested": {
        "AwesomeMessage": {
          "fields": {
            "awesomeField": {
              "type": "string",
              "id": 1
            }
          }
        }
      }
    }
  }
}
------ 

My code is
            protobuf.load("awesome.json", function(err, root) {
                if (err) throw err;
                console.log('root:', root);
                var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");  // Here:  throw Error("no such type: " + path);
                console.log('AwesomeMessage:', AwesomeMessage);
            });

Please help

**Comment by alexander-fenster** [comment]
@fordringd2008  My bad, I typed the wrong thing - JSON should go to `fromJSON`.
```js
const root = protobuf.Root.fromJSON(json);
```
here `json` is the _content_, not the filename.

**Comment by fordringd2008** [comment]
Thanks you for reply. 
But it still can not work.
My code is 

            let json = `{"nested":{"awesomepackage":{"nested":{"AwesomeMessage":{"fields":{"awesomeField":{"type":"string","id":1}}}}}}}`;
            let testAaa = JSON.parse(json); // it is OK
            console.log(testAaa);
            const root = protobuf.Root.fromJSON(json);
            console.log('root:', root);
            var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");  // Here: throw Error 
            console.log('AwesomeMessage:', AwesomeMessage);


Any wrong in my code?

**Comment by fordringd2008** [comment]
@alexander-fenster  Could you help me?

**Comment by fordringd2008** [comment]
Thank you a lot.

I update my code, seemed is OK now.


        let json = `{"nested":{"awesomepackage":{"nested":{"AwesomeMessage":{"fields":{"awesomeField":{"type":"string","id":1}}}}}}}`;
        let testAaa = JSON.parse(json); // it is OK
        console.log(testAaa);  // 
        const root = protobuf.Root.fromJSON(testAaa);  // replace json to object. it seemed ok  now
        console.log('root:', root);
        var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");  // Here: throw Error 
        console.log('AwesomeMessage:', AwesomeMessage);

**Comment by alexander-fenster** [comment]
You're welcome!
