### ISSUE TITLE
Snake case in proto file getting converted to Camel case

### ISSUE THREAD

**Issue by abhighyaa-jain** [protobufjs/protobuf.js#1465]
protobuf.js version: 6.10.1

Expected Behaviour: 
For a variable like abc_demo, 
```js proto file => abc_demo;  decoded message => abc_demo```

But the output is,
```js proto file => abc_demo; decoded message => abcDemo```

I also tried {keepCase: true}, but that is throwing error => root.load is not a function

**Comment by alexander-fenster** [comment]
Hi @abhighyaa-jain,

You can do this:

`test.proto`:
```proto
syntax = "proto3";

package test;

message Test {
  string snake_case = 1;
}
```

```js
> const protobuf = require('protobufjs');
> const root = new protobuf.Root();
> root.loadSync('./test.proto', {keepCase: true});
```

This way it will work as you expect:
```js
> testMessage = root.lookup('Test');
> testMessage.decode(testMessage.encode({snake_case: 'test'}).finish())
Test { snake_case: 'test' }   // keeps the snake case, does not change to camelCase
> testMessage.toObject({}, {defaults: true})
{ snake_case: '' }
```

Please feel free to reopen if something did not work for you.
