### ISSUE TITLE
utf8.read function producing wrong strings

### ISSUE THREAD

**Issue by masad-frost** [protobufjs/protobuf.js#1473]
protobuf.js version: 6.10.1

The `utf8.read` function seems to inserting extra unicode characters sometimes.

Here's a repro (https://repl.it/@masfrost/pbjs-bad-decode) where I check `utf8.read` against WHATWG `TextEncoder`. The repro file is not very minimal but this issue seems to be pretty common for us when decoding strings.

FYI for future readers, we monkey patched the library and forced it to use TextDecoder/TextEncoder here https://github.com/replit/crosis/blob/v5.0.3/src/fixUtf8.ts

I think maybe using the standard TextEncoder/Decoder might be the best thing to do here, encoding is just too complicated and I'm sure these standard libraries are faster. Happy to put up a PR if that's an option, otherwise, I don't really have enough time to go splunking into utf8 land.

**Comment by daviderenger** [comment]
This is still not fixed with #1486. We got a very mysterious problem where extra � was added at almost even 8000 places sometimes in some of our messages. Turns out we only got it when we had emojis in the strings.

We went the way of using TextDecoder too and it works every time.

**Comment by masad-frost** [comment]
@daviderenger do you have a test case?

**Comment by maximelkin** [comment]
`@protobufjs/utf8` is not published in npm, maybe this is why fix not working?
@alexander-fenster can you please release this packages too?

**Comment by Cubelrti** [comment]
Encountered this too, @protobufjs/utf8 is still v1.1.0 and not applying the patch.

Any update?
