### ISSUE TITLE
Error while trying with Chrome Packaged App

### ISSUE THREAD

**Issue by caioketo** [protobufjs/protobuf.js#149]
I'm trying to implement protobuff in my chrome packaged app, but when I init it it says:
"Uncaught InvalidAccessError: Failed to execute 'open' on 'XMLHttpRequest': Synchronous requests are disabled for this page. "

Any Ideas to make this work?

**Comment by kavinkamaraj** [comment]
@dcodeIO : Iam trying to do the exact same thing as caioketo and here's my code:

    StageOne = ProtoBuf.loadProtoFile("xyz.proto", function(builder) {
     });         
    Coordinates = StageOne.build("Coordinates", function (rebuilder) {
	     console.log (Coordinates); 
     });

However, when I run my chrome app for whatever reason it says 'Uncaught TypeError: Cannot read property 'build' of undefined'. So, I then printed out my StageOne variable to the console and it comes out as undefined but shouldn't there be some kind of formatting value encoded? Any help would be appreciated. P.S Your API is helping me BIG TIME for my project! :)

**Comment by dcodeIO** [comment]
You have to use the result from within the asynchronous callback:

```js
ProtoBuf.loadProtoFile("xyz.proto", function(builder) {
   var Coordinates = builder.build("Coordinates");
   ...
});
```

With an asynchronous callback, ProtoBuf.loadProtoFile doesn't return anything.

**Comment by kktheballer** [comment]
Thank you for your quick reply (this is actually the first online question I have ever asked LOL so I am super excited!!!!). But ok I ran my code and I am getting "Uncaught TypeError: builder.build is not a function". Why is that happening?

**Comment by dcodeIO** [comment]
Sorry, the API has changed meanwhile. I have updated my answer accordingly.

**Comment by kktheballer** [comment]
Thanks but my code is still not exactly doing what I want it to do. Essentially what I am trying to do is configure the Coordinates variable and say Coordinates.decode ('protobufmessage')

Here are my two approaches (both don't work as console.log(msg.text) always comes out as undefined):


Approach 1:
 try {
			   ProtoBuf.loadProtoFile("xyz.proto", function(err, builder) {
			       if (err) {
			          console.log ("Could not configure protobuf");
			       }
			       console.log ("Protobuf Configured!");
			       var Coordinates = builder.build ("Coordinates");
		               var msg = Coordinates.decode(info.data);
			       console.log (msg.text);
  });

Approach 2:
  try {
			   ProtoBuf.loadProtoFile("xyz.proto", function(err, builder) {
			       if (err) {
			          console.log ("Could not configure protobuf");
			       }
			       console.log ("Protobuf Configred!");

                                builder.build("Coordinates", function (err, rebuilder) {
			        	   if (err) {
			       	       console.log ("fail of course");
			         	   }
			        	   var msg = rebuilder.decode(info.data);
			        	   console.log (msg.text);
			       });		       
			   });

**Comment by dcodeIO** [comment]
`Builder#build` is synchronous and thus does not accept an asynchronous callback, so it rather is approach 1. It then depends on what kind of data `info.data` holds. Is it a string? An arraybuffer?

Generally speaking, your code snippets seem rather questionable to me (like not returning after handling `err`, using callbacks where they don't belong) and I find it a bit hard to answer your question based on it.

**Comment by kktheballer** [comment]
Sorry I am just completely new to this and really I am trying to base my code off of your example in GitHub. I am not returning after err for now ... just sending error messages.

 But info.data holds an arraybuffer. I thought approach 1 would work (maybe ignore the second one for now). The line that isn't working is "var msg = Coordinates.decode(info.data);" because the console.log (msg.text) just gives me undefined. Any suggestions? I tried using an arraybuffertostring function to make sure that info.data actually carried information and it does so I am a bit lost.

**Comment by dcodeIO** [comment]
What does the .proto of Coordinates look like? And what is printed to console when just doing `console.log(msg);`?

**Comment by kktheballer** [comment]
Ok so .proto is

message Coordinates {
  required int32 x = 1;
  required int32 y = 2;
  required int32 z = 3;
}

and 

Oh console.log(msg) gives me:
f {x: 1, y: 2, z: 3}
x: 1
y: 2
z: 3
__proto__: Object

Wait does that mean it decoded?

**Comment by kktheballer** [comment]
Oh wow that's amazing so it seems that msg.text gives me undefined and just msg alone gets me the whole message. That's so neat! I was using your old example using example.proto which had msg.text. I'm assuming the chrome app maybe works a little differently from just webbrowser js maybe?

**Comment by dcodeIO** [comment]
A message has all the fields defined in its .proto. The sole reason that a message might have a "text" property is, if it has such a field defined.

**Comment by kktheballer** [comment]
Wow, sorry I totally thought .text was some kind of protobuf.js thing rather than the actual field of the protobuf message itself. Thanks for all the help! 

I may be back again though!! :)
