### ISSUE TITLE
loadFromString or loadFromBuffer API

### ISSUE THREAD

**Issue by Jason8Aaron** [protobufjs/protobuf.js#1516]
When can support loadFromString or loadFromBuffer API? It is useful for browser to fetch the proto file from remote server and load proto file.

like this
```js
    const protoStr = `
    syntax = "proto3";
    package awesomepackage;
    message Message {
        repeated string phone = 1;
        optional string keyword =2;
    }`;

    const protoBuffer = Buffer.from(protoStr);

    const root1 = await protobuf.loadFromString(protoStr);
    const root2 = await protobuf.loadFromBuffer(protoBuffer);
    const root3 = await protobuf.loadFromBuffer(fs.readFileSync("./awesome.proto"));
```

**Comment by alexander-fenster** [comment]
@Jason8Aaron The first problem that will occur here is that you won't be able to support imports, so this feature will be limited to self-contained proto files with no dependencies.

As a workaround, if the remote server code is under your control, I can suggest producing a JSON proto representation (`npx pbjs -t json input.proto`), then you will be able to load this JSON with `const root = protobuf.Root.fromJSON(JSON.parse(json))`.

As a more ugly workaround, you can still make it work by hacking the existing `loadSync` method. It works, but the warranty* is void since the seal is broken.

```js
const protobuf = require('protobufjs');

protobuf.loadFromBuffer = function(buffer) {
  const fs = protobuf.util.fs;
  protobuf.util.fs = {
    readFileSync(_filename) {
      return buffer;
    }
  };
  const result = protobuf.loadSync('fake.proto');
  protobuf.util.fs = fs;
  return result;
}

protobuf.loadFromString = function(str) {
  return protobuf.loadFromBuffer(Buffer.from(str));
}
```
With this hack, your code works (with no `await` since everything is synchronous):
```js
const root1 = protobuf.loadFromString(protoStr);
const root2 = protobuf.loadFromBuffer(protoBuffer);
const root3 = protobuf.loadFromBuffer(fs.readFileSync("./awesome.proto"));
```

---
* Just kidding. There is [no warranty](https://github.com/protobufjs/protobuf.js/blob/master/LICENSE).

**Comment by Jason8Aaron** [comment]
### server.proto (client -> server)
```protobuf
syntax = "proto3";
package client;

message Chat {
    string uid = 1;
}
```
### server.proto (server -> client)
```protobuf
syntax = "proto3";
package server;

message OnChat {
    string uid = 1;
    string name = 2;
    string age = 3;
}
```

### this is a simplest transfer diagram. 
![image](https://user-images.githubusercontent.com/54534967/101437067-fd48db80-3941-11eb-9ec5-e27664d5a6e5.png)


Actrually wsServer is a cluster that contains more than one kind of server that has their own "client.proto" and "server.proto" through a ws proxy to connected with wsClient.
All message of "client.proto" and "server.proto" are no dependencies. when any proto file is changed that I don't need change the client code. Now I write the proto file first then translated to json descriptors and send json descriptors to client, it's works. I commit this issue,because I wanna skip translate step.

**Comment by Jason8Aaron** [comment]
> @Jason8Aaron The first problem that will occur here is that you won't be able to support imports, so this feature will be limited to self-contained proto files with no dependencies.
> 
> As a workaround, if the remote server code is under your control, I can suggest producing a JSON proto representation (`npx pbjs -t json input.proto`), then you will be able to load this JSON with `const root = protobuf.Root.fromJSON(JSON.parse(json))`.
> 
> As a more ugly workaround, you can still make it work by hacking the existing `loadSync` method. It works, but the warranty* is void since the seal is broken.
> 
> ```js
> const protobuf = require('protobufjs');
> 
> protobuf.loadFromBuffer = function(buffer) {
>   const fs = protobuf.util.fs;
>   protobuf.util.fs = {
>     readFileSync(_filename) {
>       return buffer;
>     }
>   };
>   const result = protobuf.loadSync('fake.proto');
>   protobuf.util.fs = fs;
>   return result;
> }
> 
> protobuf.loadFromString = function(str) {
>   return protobuf.loadFromBuffer(Buffer.from(str));
> }
> ```
> 
> With this hack, your code works (with no `await` since everything is synchronous):
> 
> ```js
> const root1 = protobuf.loadFromString(protoStr);
> const root2 = protobuf.loadFromBuffer(protoBuffer);
> const root3 = protobuf.loadFromBuffer(fs.readFileSync("./awesome.proto"));
> ```
> 
> * Just kidding. There is [no warranty](https://github.com/protobufjs/protobuf.js/blob/master/LICENSE).

**Comment by Jason8Aaron** [comment]
> @Jason8Aaron The first problem that will occur here is that you won't be able to support imports, so this feature will be limited to self-contained proto files with no dependencies.
> 
> As a workaround, if the remote server code is under your control, I can suggest producing a JSON proto representation (`npx pbjs -t json input.proto`), then you will be able to load this JSON with `const root = protobuf.Root.fromJSON(JSON.parse(json))`.
> 
> As a more ugly workaround, you can still make it work by hacking the existing `loadSync` method. It works, but the warranty* is void since the seal is broken.
> 
> ```js
> const protobuf = require('protobufjs');
> 
> protobuf.loadFromBuffer = function(buffer) {
>   const fs = protobuf.util.fs;
>   protobuf.util.fs = {
>     readFileSync(_filename) {
>       return buffer;
>     }
>   };
>   const result = protobuf.loadSync('fake.proto');
>   protobuf.util.fs = fs;
>   return result;
> }
> 
> protobuf.loadFromString = function(str) {
>   return protobuf.loadFromBuffer(Buffer.from(str));
> }
> ```
> 
> With this hack, your code works (with no `await` since everything is synchronous):
> 
> ```js
> const root1 = protobuf.loadFromString(protoStr);
> const root2 = protobuf.loadFromBuffer(protoBuffer);
> const root3 = protobuf.loadFromBuffer(fs.readFileSync("./awesome.proto"));
> ```
> 
> * Just kidding. There is [no warranty](https://github.com/protobufjs/protobuf.js/blob/master/LICENSE).


### server.proto (client -> server)
```protobuf
syntax = "proto3";
package client;

message Chat {
    string uid = 1;
}
```
### server.proto (server -> client)
```protobuf
syntax = "proto3";
package server;

message OnChat {
    string uid = 1;
    string name = 2;
    string age = 3;
}
```

### this is a simplest transfer diagram. 

![image](https://user-images.githubusercontent.com/54534967/101577186-11590f80-3a0c-11eb-9f99-d45a48f66a2d.png)


Actrually wsServer is a cluster that contains more than one kind of server that has their own "client.proto" and "server.proto" through a ws proxy to connected with wsClient.
All message of "client.proto" and "server.proto" are no dependencies. when any proto file is changed that I don't need change the client code. Now I write the proto file first then translated to json descriptors and send json descriptors to client, it's works. I commit this issue,because I wanna skip translate step

**Comment by Jason8Aaron** [comment]
@alexander-fenster 

### server.proto (client -> server)
```protobuf
syntax = "proto3";
package client;

message Chat {
    string uid = 1;
}
```
### server.proto (server -> client)
```protobuf
syntax = "proto3";
package server;

message OnChat {
    string uid = 1;
    string name = 2;
    string age = 3;
}
```

### this is a simplest transfer diagram. 

![image](https://user-images.githubusercontent.com/54534967/101578537-74e33d00-3a0c-11eb-80eb-4df61f6c8418.png)


Actrually wsServer is a cluster that contains more than one kind of server that has their own "client.proto" and "server.proto" through a ws proxy to connected with wsClient.
All message of "client.proto" and "server.proto" are no dependencies. when any proto file is changed that I don't need change the client code. Now I write the proto file first then translated to json descriptors and send json descriptors to client, it's works. I commit this issue,because I wanna skip translate step

**Comment by Jason8Aaron** [comment]
@alexander-fenster   I made one myself
```js
protobuf.loadFromString = (name, protoStr) => {
    const fetchFunc = Root.prototype.fetch;
    Root.prototype.fetch = (_, cb) => cb(null, protoStr);
    const root = new Root().load(name);
    Root.prototype.fetch = fetchFunc;
    return root;
};
```
``` js
const protobuf = require('protobufjs')
const Root = protobuf.Root;

protobuf.loadFromString = (name, protoStr) => {
    const fetchFunc = Root.prototype.fetch;
    Root.prototype.fetch = (_, cb) => cb(null, protoStr);
    const root = new Root().load(name);
    Root.prototype.fetch = fetchFunc;
    return root;
};

let protoStr = `
    syntax = "proto3";
    package awesomepackage;

    option go_package = "/awesomepackage";

    message Sub {
        repeated  string awesomeField = 1;
        optional  string name = 2;
        optional  int32 age = 3;
    }

    message AwesomeMessage {
        repeated  string awesomeField = 1;
        optional  string name = 2;
        optional  int32 age = 3;
        optional  Sub sub =4;
    }
`

protobuf.loadFromString("awesomepackage", protoStr)
    .then(root => {
        const AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");

        const buffer = AwesomeMessage.encode({ awesomeField: ["AwesomeString"], name: "asd", age: 123, sub: { awesomeField: ["AwesomeString"], name: "asd", age: 123, } }).finish();
        console.warn(buffer); // <Buffer 0a 0d 41 77 65 73 6f 6d 65 53 74 72 69 6e 67 12 03 61 73 64 18 7b 22 16 0a 0d 41 77 65 73 6f 6d 65 53 74 72 69 6e 67 12 03 61 73 64 18 7b>


        const message = AwesomeMessage.decode(buffer);
        console.warn(JSON.stringify(message)); // {"awesomeField":["AwesomeString"],"name":"asd","age":123,"sub":{"awesomeField":["AwesomeString"],"name":"asd","age":123}}
    });
```
