### ISSUE TITLE
6.11.1 has some breaking changes that are not documented

### ISSUE THREAD

**Issue by ardatan** [protobufjs/protobuf.js#1605]
protobuf.js version: 6.11.1 (seen only on npm => https://www.npmjs.com/package/protobufjs )
https://github.com/Urigo/graphql-mesh/pull/2046
When I upgraded protobufjs from 6.10.2 to 6.11.1, TS Check and unit tests are failing because of some missing TypeScript definitions and methods on `Root` class.

**Comment by alexander-fenster** [comment]
Hi @ardatan, sorry for the breakage!

Can you give more details? I believe the problem you're talking might be about the addition of `| null` in the generated `.d.ts` in some cases, but would be great to take a look at the specific proto and the corresponding `.d.ts` differences so we could see if it's a valid type change or a bug that needs to be fixed.

As a general note, TypeScript type compatibility is always complicated. Making the type more specific or fixing a bug in the type definition is almost always breaking at least for some code, and it won't be realistically possible to bump semver major for each and every typing change.

**Comment by alexander-fenster** [comment]
I double checked the generated `*.d.ts` and found that the `rule` field got missing due to the misplaced JSDoc comment. Sorry for that! I fixed that in v6.11.2. I don't see any other breaking changes in the `.d.ts` files of the protobuf library compared with v6.10.2.

**Comment by ardatan** [comment]
Thank you @alexander-fenster! That seems to fix the issue :)

**Comment by ardatan** [comment]
It is out of context but I'd appreciate if you check this PR :)
https://github.com/protobufjs/protobuf.js/pull/1592

**Comment by alexander-fenster** [comment]
We'll take a look on our next review meeting, which will likely happen next Friday (we try to do it bi-weekly but not always possible since it's obviously not a primary job for any of us here).  Thank you!
