### ISSUE TITLE
Compute size of serialized message?

### ISSUE THREAD

**Issue by npow** [protobufjs/protobuf.js#162]
Hi, is there a ByteSize() equivalent in ProtoBuf.js? Did a quick search and wasn't able to find anything.

https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message_lite#MessageLite.ByteSize.details

**Comment by GeorgePap-719** [comment]
Hello @dcodeIO , i stumbled upon this issue and i'm wondering how did you implement `calculate` without serializing the message itself first? I'm looking through the commit but i'm having hard time to underrtand the implementation details. 

Thanks in advance for any answer!

**Comment by dcodeIO** [comment]
Iirc there are calculate functions for the basic ingredients like varints and strings, which are used by the calculate methods of fields, which again are iterated and summed by the calculate methods of messages.
