### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by hyskylord** [protobufjs/protobuf.js#1635]
protobuf.js version: 6.11.2

Hi, I'm using a JSON descriptor to decode the messages from server. Most of the messages are decoded succesfully, but I encountered an index out of range error when decoding the following message:

The raw data (indent for readability): 1230 120E08C19A0C1000180028E5B5183000 120E08C29A0C1000180028C9B6183000 1A06E5B518C9B618 20C19A0C 2800 3002

Error message: index out of range: 46 + 8 > 50

I have checked the data by hand and it seems perfectly matching the descriptor file. The method related to the data is the following:

        "MethodInfo": {
          "fields": {
            "error": {
              "type": "Error",   //This doesn't appear in the raw data so I guess it doesn't matter?
              "id": 1
            },
            "field2": {
              "rule": "repeated",
              "type": "Customed",
              "id": 2
            },
            "field3": {
              "rule": "repeated",
              "type": "uint32",
              "id": 3
            },
            "field4": {
              "type": "uint32",
              "id": 4
            },
            "field5": {
              "type": "uint32",
              "id": 5
            },
            "field6": {
              "type": "uint32",
              "id": 6
            },
            "field7": {
              "rule": "repeated",
              "type": "uint32",
              "id": 7
            },
            "field8": {
              "rule": "repeated",
              "type": "uint32",
              "id": 8
            },
            "field9": {
              "rule": "repeated",
              "type": "uint32",
              "id": 9
            }
          }
        },
        "Customed": {
          "fields": {
            "cfield1": {
              "type": "uint32",
              "id": 1
            },
            "cfield2": {
              "type": "uint32",
              "id": 2
            },
            "cfield3": {
              "type": "uint32",
              "id": 3
            },
            "cfield4": {
              "rule": "repeated",
              "type": "Customed2",    //This also doesn't appear in the raw data.
              "id": 4
            },
            "cfield5": {
              "type": "uint32",
              "id": 5
            },
            "cfield6": {
              "type": "bool",
              "id": 6
            },
            "cfield7": {
              "rule": "repeated",
              "type": "uint32",
              "id": 7
            }
          }
        },

**Comment by hyskylord** [comment]
Also tried to use the online decoding service in https://protogen.marcgravell.com/decode to verify the binary data and the result fits the schema.

**Comment by hyskylord** [comment]
Solved.

**Comment by trandaison** [comment]
@hyskylord How did you solve your problem?
