### ISSUE TITLE
how to import pb from other folder

### ISSUE THREAD

**Issue by q774221810** [protobufjs/protobuf.js#1639]
this is a folder 
/pb/main.proto
/base.proto

In  main.proto,i want to import base.proto,
and creat a message,such as,

```
import "pb/base.proto";
message test{
pb.Page page=255
}
```

i want to use pbjs to generate the file,but i got a error that saying no such Type or Enum 'pb.Page' in Type .
how can i import base.proto and use base.proto

**Comment by tilakraj9560** [comment]
hey did you get the solution?

**Comment by NijatInHIT** [comment]
> hey did you get the solution?

hey did you get the solution?

**Comment by q774221810** [comment]
> > hey did you get the solution?
> 
> hey did you get the solution?

yes ,thank u

**Comment by NijatInHIT** [comment]
> > > hey did you get the solution?
> > 
> > 
> > hey did you get the solution?
> 
> yes ,thank u

Wow🤩  Could you share your solution?

**Comment by CCZX** [comment]
> > > > hey did you get the solution?
> > > 
> > > 
> > > hey did you get the solution?
> > 
> > 
> > yes ,thank u
> 
> Wow🤩 Could you share your solution?
You can try to pass parameters through -p on the npm script command that generates the protocol file, the parameter value is the root directory of your prototype file: 

```
pbjs -t static-module -w commonjs -p /your-root-dir -o proto.js index.proto
```
