### ISSUE TITLE
Uncaught TypeError: Cannot convert a BigInt value to a number in serializeBinary()

### ISSUE THREAD

**Issue by farnasirim** [protobufjs/protobuf.js#1645]
protobuf.js version: ^6.10.0
Chrome Version 89.0.4389.114 (Official Build) (64-bit)

When calling .serializeBinary() on a proto, I'm getting the following error instead of the actual serialization:
```
google-protobuf.js:409 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.floor (<anonymous>)
    at jspb.BinaryEncoder.writeUnsignedVarint64 (google-protobuf.js:409)
    at jspb.BinaryWriter.writePackedUint64 (google-protobuf.js:471)
    at proto.my_pb.Obj3.serializeBinaryToWriter (my_pb.js:1304)
    at jspb.BinaryWriter.writeMessage (google-protobuf.js:451)
    at proto.my_pb.Obj2.serializeBinaryToWriter (my_pb.js:1543)
    at jspb.BinaryWriter.writeMessage (google-protobuf.js:451)
    at Function.proto.my_pb.Obj.serializeBinaryToWriter (my_pb.js:4540)
```
And the link to the source takes me here:
```
jspb.BinaryEncoder.prototype.writeUnsignedVarint64=function(a){goog.asserts.assert(a==Math.floor(a));goog.asserts.assert(0<=a&&a<jspb.BinaryConstants.TWO_TO_64);jspb.utils.splitInt64(a);this.writeSplitVarint64(jspb.utils.split64Low,jspb.utils.split64High)};
```

**Comment by alexander-fenster** [comment]
The stack points to the official protobuf implementation from Google, it does not look related to protobuf.js at all. To serialize a protobuf.js object, use `TypeName.encode(obj).finish()`, where `TypeName` is the type of your object.

**Comment by farnasirim** [comment]
@alexander-fenster Perhaps by "serialize" you are referring to encoding a JSON as a pbjs object? I am trying to get the byte representation of a pbjs object that I already have.

**Comment by alexander-fenster** [comment]
@farnasirim I actually mean that there are two incompatible protobuf libraries for JS: this one and the official one from Google. They produce the same binary representation but different API, and the stack you posted points to the usage of google-protobuf library (the official one).
