### ISSUE TITLE
Protobuf loadSync alternative in browser/webpack/browserify?

### ISSUE THREAD

**Issue by Reiszecke** [protobufjs/protobuf.js#1648]
protobuf.js version: 6.11.2

I am trying to use this lib as part of a bigger project in a browser environment.

I pack the app via `webpack` and run into `Uncaught Error: not supported`, `at loadSync`. This is most likely caused due to 

https://github.com/protobufjs/protobuf.js/blob/95b56817ef6fb9bdcb14d956c159da49d0889bff/src/root.js#L245

is this done to avoid blocking the thread or is it absolutely impossible to synchronously load definitions in browsers? I couldn't find any discussion on this issue - if one exists, I would love to read into it and look for alternatives so I don't have to rewrite my code entirely 😐

**Comment by Reiszecke** [comment]
I tried overriding the node-check but ran into further issues. I checked whether you could just parse a string and https://github.com/protobufjs/protobuf.js/issues/1516#issuecomment-738645410 seems to work for that.

**Comment by alexander-fenster** [comment]
`loadSync` uses Node.js `fs` module to read files from the filesystem. In the web environment, an alternative approach would be to use `pbjs` tool with `-t json` to compile your proto files to JSON, then you will be able to `require` the JSON file and pass it to `protobuf.Root.fromJSON(...)`.

This is how we do it so it works both in Node.js and in webpack: https://github.com/googleapis/nodejs-speech/blob/main/src/v1/speech_client.ts#L168

**Comment by Reiszecke** [comment]
Thank you for the information Alexander!
