### ISSUE TITLE
index out of range: 34 + 40 > 44 on decode same proto encoded buffer

### ISSUE THREAD

**Issue by mingxxming** [protobufjs/protobuf.js#1685]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>
error on decode same proto encoded buffer

<please provide a code snippet for reproduction>

### proto:
message UpdatePosCmd {
	int64 tg_posx = 1;
	int64 tg_posy = 2;
	int64 tg_posz = 3;
	int64 posx = 4;
	int64 posy = 5;
	int64 posz = 6;
}

let cmd = new UpdatePosCmd();
cmd.tgPosx = -80104618928n;
cmd.tgPosy = 167502018n;
cmd.tgPosz = 2624198282n;
cmd.posx = -90864319998n;
cmd.posy = 170625265n;
cmd.posz = 9496643105n;
console.log("---------------", UpdatePosCmd.decode(UpdatePosCmd.encode(cmd).finish()));

<please paste the stack trace of the error if applicable>

RangeError: index out of range: 34 + 40 > 44
    at indexOutOfRange (protobuf.js:4857:12)
    at Reader.skip (protobuf.js:5199:19)
    at Reader.skipType (protobuf.js:5225:18)
    at Function.decode (gen/bundle.js:13633:24)
    at Function.updatePos (client/net/webapi.js:147:60)
    at launch.js:10:17
    at executeModule (puerts/modular.js:50:9)
    at require (puerts/modular.js:99:17)
    at chunk:2:17

**Comment by SichorChing** [comment]
I have same error, how to resolve this?
