### ISSUE TITLE
deserialization trouble

### ISSUE THREAD

**Issue by chris-kruining** [protobufjs/protobuf.js#1690]
Hi,

I am developing a gRPC library over at https://github.com/FYN-Software/grpc/pull/16.
And I am running into the issue that most of the time my deserialization just works fine, sometimes I get `Invalid wire type: 7`, and some other times it just does not want to work at all.

I have done some debugging and I am fairly certain this has to do with my header interpretation.

I have tried to get an implementation with a var-int reader and a uint32 reader but just no success with all messages.

I can get it to work for a few payloads, but then not others.

Could you maybe help my by pointing out my error in logic?

**Comment by chris-kruining** [comment]
I should mention, my lib is trying to implement gRPC not gRPC-web

**Comment by chris-kruining** [comment]
ping

**Comment by chris-kruining** [comment]
It seems I have fixed it, simply buffering and making sure only whole messages get de-serialized seems to be the key to success, who would have thunk...

**Comment by a554878526** [comment]
> It seems I have fixed it, simply buffering and making sure only whole messages get de-serialized seems to be the key to success, who would have thunk...

I also encountered the same error. How did you fix it

![image](https://github.com/protobufjs/protobuf.js/assets/70568691/7059cbfe-3d28-4a83-9e78-f83a121fc66e)

**Comment by chris-kruining** [comment]
It's been two years since I worked on this, so I am afraid I wont be much help. you could try to dig through my commits and see if that helps. other than that I don't know
