### ISSUE TITLE
socket.send?

### ISSUE THREAD

**Issue by SirZach** [protobufjs/protobuf.js#175]
I'm trying to understand the docs and I can't seem to get past this point -

```
// And send it over the wire:
var socket = ...;
socket.send(buffer.toArrayBuffer()); // node.js: buffer.toBuffer()
```

If I create a socket in node, I have to use the net module and I can create a TCP socket by doing <code>var socket = new net.Socket();</code>

From there, I can establish a connection to my server but doing <code>socket.send</code> is an invalid method and doing <code>client.write(buffer.toArrayBuffer());</code> complains about invalid data.

Any help would be much appreciated. Thanks!

**Comment by talha131** [comment]
@SirZach Thanks. It also took me a long time to figure out `toBuffer()`. :+1:
