### ISSUE TITLE
pbjs cli pkg.version not updated since 6.9.0

### ISSUE THREAD

**Issue by vedantnaik** [protobufjs/protobuf.js#1758]
protobuf.js version: 6.11.3 (possibly affects every version after 6.9.0)

Running pbjs command logs incorrect pkg version of protobuf.js version ([stderr line](https://github.com/protobufjs/protobuf.js/blob/b130dfd4f06b642d4b7c3ccc9f3f9fb6a6e6ed0d/cli/pbjs.js#L91))

To reproduce - install latest version of protobuf.js and run pbjs on terminal
```sh
❯ pbjs
protobuf.js v6.9.0 CLI for JavaScript
```

Potential correction:
Should version be updated in [package.json here](https://github.com/protobufjs/protobuf.js/blob/b130dfd4f06b642d4b7c3ccc9f3f9fb6a6e6ed0d/cli/package.json#L2)?

**Comment by stefnotch** [comment]
This seems to have been fixed
