### ISSUE TITLE
Data has no default value

### ISSUE THREAD

**Issue by gdoudeng** [protobufjs/protobuf.js#1782]
protobuf.js version: 6.11.2

When I use proto3, I use pbjs to compile the proto file into js, such as such a protocol

````
syntax = "proto3";
package com.message.proto.user;
option java_package = "com.message.proto";
option java_outer_classname = "UserProtoBuf";

message UserInfo {
   bool isVerified = 1;
   int32 sex = 2;
}
````
```js
// The server pushes the message and performs protocol decoding on the client side
const protocolBuf = com.message.proto.user.UserInfo.decode(new Uint8Array(data)); // data is a byte stream
```

If the server does not set isVerified when pushing UserInfo, the protocolBuf will not have the field isVerified = false, but the entire field of isVerified does not exist and protocolBuf. The result I hope is that when the server has a field that is not set, the client side There can be default values, such as bool is false, int32 is 0, string is ""

**Comment by gdoudeng** [comment]
```
pbjs --no-verify --no-convert --no-beautify --no-delimited --dependency protobufjs/minimal.js --target static-module --wrap commonjs -r ${filename}_pb --out ${PROTO_JS_PATH}/${filename}_pb.js ${PROTO_PATH}/${filename}.proto
```

**Comment by gdoudeng** [comment]
Can someone answer the question？

**Comment by zhubinsheng** [comment]
ｈｅｌｌｏｗ　，ｑａｑｈｏｗ　ｔｏ　ｆｉｘ
