### ISSUE TITLE
Dist folder is missing in https://github.com/protobufjs/protobuf.js/archive/refs/tags/protobufjs-v7.1.0.zip

### ISSUE THREAD

**Issue by basgroot** [protobufjs/protobuf.js#1794]
protobuf.js version: 7.1.0

1. Go to release page https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.1.0
2. Download zip.

Expected:
Dist folder in downloaded archive (with protobuf.js and protobuf.min.js), like there was one in https://github.com/protobufjs/protobuf.js/archive/refs/tags/protobufjs-v7.0.0.zip

Actual:
No dist folder in the archive.

Maybe I'm looking at the wrong place. Then I'd like to have some guidance.

Thanks!

**Comment by basgroot** [comment]
![image](https://user-images.githubusercontent.com/3939334/187049782-7752f97e-b1d3-4234-b1da-7be8f95412b4.png)

Maybe related. This URL doesn't exist:
<https://cdn.jsdelivr.net/gh/dcodeIO/protobuf.js@7.1.0/dist/protobuf.js>

This URL exists:
<https://cdn.jsdelivr.net/gh/dcodeIO/protobuf.js@6.11.0/dist/protobuf.js>

**Comment by alexander-fenster** [comment]
Yeah we removed it in #1766 because normally you don't commit generated files (the `dist` folder exists in the npm archive though). Apparently it indeed broke the cdn links. Uh oh. Do you have an idea if we could make it work without actually committing it back? Maybe some cdn service that could read an npm package and not a source repo?

```
$ echo {} > package.json
$ npm install protobufjs
$ ls node_modules/protobufjs/dist/
light			minimal			protobuf.js		protobuf.js.map		protobuf.min.js		protobuf.min.js.map
```

**Comment by alexander-fenster** [comment]
After quick googling: https://unpkg.com/protobufjs@7.1.0/dist/protobuf.js - will this one work for you?

I can update the links in the readme.

**Comment by basgroot** [comment]
That is a good solution, thanks!
I'll close the issue.

**Comment by basgroot** [comment]
Still one issue remaining:
https://unpkg.com/protobufjs@**7.1.1**/dist/protobuf.js
is the same as
https://unpkg.com/protobufjs@**7.1.0**/dist/protobuf.js
(except for the generation date)

The new file (7.1.1) states in the header "protobuf.js v**7.1.0** (c) 2016, daniel wirtz" and doesn't include the fix with **var defaultAlreadyEmitted**.

**Comment by alexander-fenster** [comment]
> Still one issue remaining: https://unpkg.com/protobufjs@7.1.1/dist/protobuf.js is the same as https://unpkg.com/protobufjs@7.1.0/dist/protobuf.js (except for the generation date)
> 
> The new file (7.1.1) states in the header "protobuf.js v**7.1.0** (c) 2016, daniel wirtz" and doesn't include the fix with **var defaultAlreadyEmitted**.

Interesting, indeed it does not. I will try to figure out why :) Thanks for pointing out!
