### ISSUE TITLE
Missing types from 'Long' in generated .d.ts file

### ISSUE THREAD

**Issue by ffflorian** [protobufjs/protobuf.js#1796]
protobuf.js version: 7.1.0

Expected behaviour:
- protobuf file converted with `pbts` adds an import from `Long` in the generated `.d.ts` file, e.g.
```ts
import Long = require('long');
```

Actual behaviour:
- no import was found

Used command:
```js
pbts --out proto/export.d.ts --no-comments proto/export.js
```

**Comment by alexander-fenster** [comment]
Yeah, it seems the import got lost in a sequence of refactors. Adding it back in #1802.

**Comment by ffflorian** [comment]
Thank you!
