### ISSUE TITLE
Load .proto file content from variable

### ISSUE THREAD

**Issue by mariusmuntean** [protobufjs/protobuf.js#1871]
protobuf.js version: 7.2.2

I have a use case where the users dynamically define the protobuf definition of the messages to be desialized/deserialized.
Right now this forces me to first store the input to a temporary .proto file and then call load(tempFilePath) just o be able to work with it.

Ideally I would be able to call load with a string variable that already contains the content of a .proto file. E.g.
```js
load({definition: myProtoDefinition}, ...)
```

**Comment by acode-x** [comment]
```js
const protofile = "syntax = \"proto3\";\
package awesomepackage;\
message AwesomeMessage {\
    string awesome_field = 1;\
    int32 awesome_value = 2;\
}";

var root = new protobuf.Root();
protobuf.parse(protofile, root, { keepCase: true, alternateCommentMode: false, preferTrailingComment: false });
root.resolveAll();

var AwesomeMessageBuilder = root.lookup("awesomepackage.AwesomeMessage");
```

Hope this helps.

**Comment by mariusmuntean** [comment]
How did I miss this? 😅
Thank you
