### ISSUE TITLE
extensions not handled correctly? 

### ISSUE THREAD

**Issue by activequant** [protobufjs/protobuf.js#197]
Hi there, 

I have a use case with protobuf extensions. It seems ProtoBuf.js doesn't parse my messages correctly. 

Everything works as expected on our server's Java side and components send messages between each other. My JavaScript client complains. 

Here's the error message when I send from Java a ComponentStatus message: 

```
.transport.protocol.Event Error: Missing at least one required field for 
Message .transport.protocol.Event: .transport.protocol.ComponentAlert.event"
```

You can see, ProtoBuf.js complains about a missing ComponentAlert field, which it shouldn't. 

Consider my corresponding proto file: 

```
package transport.protocol; 

option java_outer_classname = "StormEvents";

enum RAG {
    RED = 1;
    AMBER = 2; 
    GREEN = 3;  
}


/** Events **/ 

message Event {

    extensions 100 to 1000;

    enum Type {
        ComponentStatus = 5; 
        ComponentAlert = 6; 
    } 

    required Type type = 1;
    required int64 timestamp = 2;   
    required int64 eventId = 3; 
}

message ComponentStatus {   
    required string name = 2; 
    required RAG status = 3;  

    extend Event {
        required ComponentStatus event = 105; 
    }    
}

message ComponentAlert {    
    required string name = 2;
    required string alertText = 3;  

    extend Event {
        required ComponentAlert event = 106; 
    }    
}
```

I try to parse my message with ProtoBuf.js like this: 

```
  var ProtoBuf = dcodeIO.ProtoBuf;
  msgBuilder = ProtoBuf.loadProtoFile("proto/events.proto");
  eventBuilder = msgBuilder.build("transport.protocol.Event");  
  compStatBuilder = msgBuilder.build("transport.protocol.ComponentStatus");  
```

and later, when I get a message, I try to parse the payload: 

```
  if(destinationName=="ADMIN"){

    // ok, admin bus message, let's decipher it ... 
    try {
        var msg = eventBuilder.decode(payload);
        var msg2 = compStatBuilder.decode(payload);
         updateStatusBar("Server time: " + unixToStr(msg.timestamp) + msg2.name);
    } catch (e) {
        if (e.decoded) { // Truncated
                myMessage = e.decoded; // Decoded message with missing required fields
            alert(myMessage + " " + e);
            } else { // General error
            alert("General error " + e);
            }
    }   
  }

```

On my server side, I do: 

```
StormEvents.ComponentStatus.Builder b = StormEvents.ComponentStatus.newBuilder();
b.setName(componentName); 
b.setStatus(rag);
        // 
StormEvents.Event.Builder c = StormEvents.Event.newBuilder();
c.setType(Type.ComponentStatus);        
c.setExtension(ComponentStatus.event, b.build());
c.setTimestamp(UniqueTimeStampGenerator.getInstance().now());
c.setEventId(UniqueTimeStampGenerator.getInstance().now());     
```

I am a bit lost, as my Java and .NET components message with each other very well ...

For some reason, it expects to find a ComponentAlert event in my message, but I send a ComponentStatus and that one does add a ComponentAlert to our extended class. I guess, there's some registry somewhere, where ProtoBuf.js registers fields of extensions and it doesn't get it that some extensions require different fields than others. 

I tried already to declare the "event" field as optional, didn't work either. If I do so, I get: 

```
General error Error: Illegal wire type for field 
Message.Field .transport.protocol.ComponentStatus.name: 0 (2 expected)
```

Maybe it has to do with my way of working with extensions, as I can access fields in my "msg" object ... 

Thanks a lot for some input

**Comment by cslxxwilliam** [comment]
the extension handling is tricky in the ProtoBuf3. Is it easier in the latest version?
