### ISSUE TITLE
Latest protobuf release not listed on CDNs

### ISSUE THREAD

**Issue by basgroot** [protobufjs/protobuf.js#2004]
protobuf.js version: 7.3.1

**Steps**

1. Load https://cdn.jsdelivr.net/npm/protobufjs/dist/

**Expected**
The distro of 7.3.1 is listed: https://cdn.jsdelivr.net/npm/protobufjs@7.3.1/

**Actual**
The old distro 7.3.0 is listed.

The same applies for https://unpkg.com/protobufjs@7.3.1/dist/protobuf.min.js, which returns `Cannot find package protobufjs@7.3.1`, where https://unpkg.com/protobufjs@7.3.0/dist/protobuf.min.js does load the script.

**Comment by basgroot** [comment]
..and the third one https://cdnjs.com/libraries/protobufjs, which also lists 7.3.0 as latest.

**Comment by dcodeIO** [comment]
Can confirm this issue. Appears the tooling we have in place only publishes to GitHub releases, but not to npm.

@protobufjs/maintainers : How was this done more recently? With a manual publish? If so, I'd need access to the `protobufjs-cli` package eventually, which is currently exclusively owned by google-wombot.

**Comment by alexander-fenster** [comment]
I normally published both `protobufjs` and `protobufjs-cli` manually using the `npm publish` command using the internal instance of [wombat dressing room](https://github.com/GoogleCloudPlatform/wombat-dressing-room) NPM proxy. The interesting part here is that there was no changes in the process between 7.3.0 and 7.3.1, so I cannot say off the top of my head why the latest version won't get listed on CDNs :(

@sofisl Hi, long time no see :) Can you please run `npm publish` for v7.3.1, and also grant access to `protobufjs-cli` to Daniel (https://www.npmjs.com/~dcode)?

**Comment by sofisl** [comment]
Hi @alexander-fenster, seems like protobuf.js is now on 7.3.1 as latest! As for adding dcode, I don't think I can (I only have write access on this repo?)

**Comment by steve9164** [comment]
Hi protobufjs maintainers. The 7.3.1 npm release is missing the dist folder. As far as I can tell this is a mistake - maybe the build processes needed before releasing didn't run properly. Would it be possible to release a 7.3.2 with this dist folder re-instated?

**Comment by basgroot** [comment]
Thank for investigating this. Looks like the image in NPM is now showing the latest version: <img src="https://img.shields.io/npm/v/protobufjs.svg?logo=npm" alt="">.

But as @steve9164 mentioned, this link lacks the dist folder: https://cdn.jsdelivr.net/npm/protobufjs@7.3.1/
The 7.3.0 has one: https://cdn.jsdelivr.net/npm/protobufjs@7.3.0/dist/

Same for this CDN: https://unpkg.com/protobufjs@7.3.1/dist/protobuf.min.js

**Comment by dcodeIO** [comment]
Published a 7.3.2 manually now.

@sofisl : Regarding adding me to the protobufjs-cli package, I think that someone with access to Google's npm proxy would need to log in with google-wombot on npm, and add [me](https://www.npmjs.com/~dcode) to the protobufjs-cli package. Is separate from GitHub.

**Comment by basgroot** [comment]
Thanks. All three are showing the latest again!

https://cdn.jsdelivr.net/npm/protobufjs/dist/
https://unpkg.com/browse/protobufjs/dist/
https://cdnjs.com/libraries/protobufjs/dist/

**Comment by eKerney** [comment]
Seems like the dist folder is again missing.
Navigating to: [https://cdn.jsdelivr.net/npm/protobufjs/dist/ ](https://cdn.jsdelivr.net/npm/protobufjs/dist/ )
> Couldn't find the requested file /dist/ in protobufjs.

**Comment by danielbankhead** [comment]
Tracking: https://github.com/protobufjs/protobuf.js/issues/2022
