### ISSUE TITLE
U64 deserialization confusion

### ISSUE THREAD

**Issue by florianmarkusse** [protobufjs/protobuf.js#2021]
protobuf.js version: 7.3.2

Hi there, I am confused about the deserialization of the u64 field in a protobuf message.

Confusing behavior:
I am wondering that when deserializing a `u64` field from a protobuf message, the result can either be a `Number` or a `Long`. A javascript `Number` has a smaller range than a `u64`, so why is it even a possibility to be deserialized into a `Number`?

Moreover, can someone describe to me the way the deserializer decides to create a `Number` or a `Long` object? It seems to me that there is no logic, a u64 that is small enough to fit into e `Number` can be deserialized into a `Number` but sometimes it also is turned into a `Long` object.

I hope this is clear and thanks for your time :)

**Comment by dcodeIO** [comment]
Currently, long.js is an optional dependency, in that, say, if `require("long")` throws, it's not used and a `number` is returned. If long.js is available, a `Long` is returned, always.

**Comment by florianmarkusse** [comment]
Hey,
Thanks for your quick response! That clarifies my problem, thanks again :)
