### ISSUE TITLE
v7.3.3 release is missing `dist` directory

### ISSUE THREAD

**Issue by ggetz** [protobufjs/protobuf.js#2022]
protobuf.js version: 7.3.3 (also occurred in v7.3.1)

The latest release is missing the `dist` directory when installed via npm. 

```
✘ [ERROR] Could not resolve "protobufjs/dist/minimal/protobuf.js"

    packages/engine/Source/Core/GoogleEarthEnterpriseMetadata.js:1:26:
      1 │ import * as protobuf from "protobufjs/dist/minimal/protobuf.js";
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Is this purposeful? If it is, we'll update to the new path. But it does not appear in the changelog, and the `dist/` path is still listed in `package.json` under `files`.

See https://github.com/CesiumGS/cesium/issues/12143

**Comment by danielbankhead** [comment]
My mistake, I will resolve this shortly

**Comment by ggetz** [comment]
Thanks @danielbankhead!

**Comment by danielbankhead** [comment]
Published! `dist/` should be available now. Additionally, to prevent this from happening in the future I've improved our `publish` script.
