### ISSUE TITLE
cli filter does not handle nested namespaces

### ISSUE THREAD

**Issue by timdream** [protobufjs/protobuf.js#2032]
protobuf.js version: 7.4.0, protobufjs-cli 1.1.3

Attempt to use the feature implemented in #1840 resulted in an error ignoring the filter

```
The filter not work, please check whether the file is correct: package not foud filtertest.filtertest.NeedMessage2
```

This can be reproduced by updating test files https://github.com/protobufjs/protobuf.js/blob/master/tests/data/cli/test-filter.proto
and
https://github.com/protobufjs/protobuf.js/blob/master/tests/data/cli/filter.json

change `package filtertest;` to `package filtertest.filtertest;` and the corresponding message names in `filter.json`.

**Comment by d-enk** [comment]
duplicate #1854
