### ISSUE TITLE
importing inner package protos leads to duplicate names

### ISSUE THREAD

**Issue by buschtoens** [protobufjs/protobuf.js#40]
Consider these [`.proto` files](https://github.com/silvinci/node-spotify-web/tree/protobufjs-issue/proto). Relevant are all files starting with `playlist4`. They depend on each other, so they import each other and use the same namespace.

When [trying to build them](https://github.com/silvinci/node-spotify-web/blob/protobufjs-issue/lib/schemas.js), everything starts crashing down on the first `import` statement.
The `import`-less files (`playlist4meta.proto` and `playlist4issues.proto`) work well. But as soon as files are loaded, that depend on other files in their package I get errors like `Error: Duplicate name in namespace Namespace .spotify.playlist4.proto: ListChecksum`.

`ListChecksum` is defined in `playlist4meta.proto`. Upon importing it in `playlist4ops.proto`, which intends to use exactly this type, it is _redeclared_ and provokes the error.

Is this a bug or am I just too stupid?

Some background information: I'm trying to update @TooTallNate's [node-spotify-web](https://github.com/TooTallNate/node-spotify-web) to use your great ProtoBuf.js.

**Comment by bsandro** [comment]
Still doesn't work for me - latest protobufjs, same error (browser version). Works just fine on a local webserver but fails instantly on remote - could the network latency be an issue for that?
