### ISSUE TITLE
Message: Iterate over fields / Retrieve keys

### ISSUE THREAD

**Issue by buschtoens** [protobufjs/protobuf.js#41]
Currently I don't see a way to iterate over a message or retrieve all of its keys. They need to be known.
Is this intended by design to prevent a dirty coding style or is it just not implemented yet?

``` js
var msg = Message.decode(data);

// Something like this...
msg.keys().forEach(function(key) {
  console.log(key, msg.get[key];
});
// ...or this...
msg.keys.forEach(function(key) {
  console.log(key, msg.get[key];
});
// ...or this would be handy.
Object.keys(msg).forEach(function(key) {
  console.log(key, msg[key];
});
```

**Comment by ShuzhanYang** [comment]
> A message includes each field's value as a standard property, so you can actually already use Object.keys to iterate over them.
> 
> If you need more than that, take a look at using [reflection](https://github.com/dcodeIO/ProtoBuf.js/wiki/Reflection).

Hello dcodeIO,
Would you mind telling some hints on building a reflection?
The link: https://github.com/dcodeIO/ProtoBuf.js/wiki/Reflection seemed to have been removed.
Thanks!
