### ISSUE TITLE
Whats wrong with this buffer? (how to decode a protobuf buffer by hand)

### ISSUE THREAD

**Issue by filipednb** [protobufjs/protobuf.js#55]
Trying to decode: 

`0a 0d 08 f9 27 12 02 4f 4b 18 8a 8c 06 20 4e`

with this message:

```
message BuyInResponse {
   enum Code {
        OK = 0;
        ERROR = 1;
        AUTH_ERROR = 2;
    }

    repeated PaymentResponseElement response = 1;
}
message PaymentResponseElement {
    optional int64 pnPaymentId = 1;
    optional string messageCode =2;
    optional int64 balanceAfterTransaction = 3;
    optional int32 version = 4;
}
```

Getting this error:
`Error: Illegal wire type for field Message.Field.core.comm.message.int2s.PaymentResponseElement.messageCode: 2 (0 expected)`

**Comment by venkatpathapati** [comment]
I have problem with extraction of string values from binary data.
Following is the structure to extract values and corresponding binary data also. 
9 {
  1: "106671829932240464836"
  4: "Vijayakrishnasai Gudavalli"
}

4a 33 0a 15 31 30 36 36 37 31 38 32 39 39 33 32 32 34 30 34 36 34 38 33 36 22 1a 56 69 6a 61 79 61 6b 72 69 73 68 6e 
61 73 61 69 20 47 75 64 61 76 61 6c 6c 69

**Comment by venkatpathapati** [comment]
Can any one help me to how to decode the binary data as specified in above comment..

**Comment by venkatpathapati** [comment]
How do we differentiate length delimited string, bytes, sub messages in binary data..Can any one help me how to parse the binary data

**Comment by strngr** [comment]
@venkatpathapati There is no other way to differentiate string and submessage except it's content. But even content may be confusing. So if you haven't schema you only can try to predict what message is and try to decode it.

**Comment by mariepascale** [comment]
I am trying to get a value in Redis which has been encoded in C# using protobuf.  I have the .proto file.  I need to access this value in a node app.  I am able to get this value from Redis using a key in the node app.  I can decode the value from Redis using protobufjs but, when I console log  the data some of the data contains something like this \n�\u0001.  Is the it corrupt?  Is it encrypted?  How do I fix this?

**Comment by krforgit** [comment]
I am getting an index out of range exception,
when I am subscribing a message from a server which is a console application,
this is the code snippet which is sending the message

![image](https://user-images.githubusercontent.com/31538061/29975085-258112c6-8f03-11e7-982b-3a45dcfe861a.png)

and the below is the JS snippet where the data is recieced but on continous recieving the protobufjs is throwing an index out of range exception at protobufjs\src\reader.js :13:12

![capture](https://user-images.githubusercontent.com/31538061/29975218-9391d872-8f03-11e7-99c7-6b3230bd7ca4.PNG)

and the exception is 
![capture1](https://user-images.githubusercontent.com/31538061/29975405-3a0f3a0a-8f04-11e7-85f7-c61c907a24e1.PNG)

can any one help me in decoding the message getting from the server continously.

**Comment by dcodeIO** [comment]
When sending and receiving multiple messages, use length delimited messages, because otherwise the decoder doesn't know where one message ends and another one starts. protobuf.js provides `Message#decodeDelimited` for this purpose (your server then has to send delimited messages as well, of course). Now, you basically want a buffer on the client side that collects all the so far received data. You'd then put this into a `protobuf.Reader` and provide it, instead of a buffer, to `Message#decodeDelimited` so you can find out how many bytes of the buffer have been read through inspecting `Reader#pos` afterwards. Cut that chunk away, rinse and repeat.
