### ISSUE TITLE
toArrayBuffer question

### ISSUE THREAD

**Issue by ucchen** [protobufjs/protobuf.js#56]
Hello!
here is my test code.

``` js
var test = new protoObject({
      "id": 130,
      "name": "abc"
});
var buff = test.encode(); 
 var arrayBuffer = buff.toArrayBuffer();
var _uint16Buffer = new Uint16Array(arrayBuffer);
```

but, get an error when i new Uint16Array. the log said that arrayBuffer is a invalid arguments. why arrayBuffer is an invalid arguments? but, if i do this var _uint8Array = new Uint8Array(arrayBuffer), it is ok. what's wrong of that? arrayBuffer is a  ArrayBuffer? if arrayBuffer is a ArrayBuffer, why i can't new Uint16Array?

here is my second test code

``` js
var array = new Uint8Array(arrayBuffer);
var str = String.fromCharCode.apply(null, array);
i need to change arrayBuffer to string and send that string to server. but server receive a wrong data(string is right, but int is wrong).
such as when i send this struct to server
var test = new protoObject({
     "id": 130,
     "name": "abc"
}) 
```

server receive such struct
id: 16706
name: "abc"

id's data isn't right, but string data is ok.
why?

**Comment by kktheballer** [comment]
Ucchen. I am having a similar problem with my code as well. Do you by anychance have the code that you used to send the str via a socket. I am trying to do what you are doing but my python script is not recognizing the string that I am sending to it.

**Comment by ucchen** [comment]
doesn't recognizing the string? can you post more detail?

**Comment by kktheballer** [comment]
var commandmessage = new MCM ({
				"carrier_freq": 92343.3,
				"num_spurs": 33333,
			    });
				   
				   console.log (commandmessage);
				   var byteBuffer = commandmessage.encode();
				   var buffer = byteBuffer.toArrayBuffer();


chrome.sockets.udp.send(socketId, byteBuffer, "0.0.0.0", 9994, function(sendInfo) {
			    console.log ("PYTHON SIMULATOR INITIATED!");
			    console.log("sent " + sendInfo.bytesSent + " bytes");
		    }); 
		    }catch (err) {
			console.log ("No data encoded");
		    }
Above is my code to send out the protobuf message
and below is my code in python to receive the protobuf message...


class MyUDPHandler(SocketServer.BaseRequestHandler):
   

    def handle(self):
        data = self.request[0].strip()
        socket = self.request[1]
        print "{} wrote:".format(self.client_address[0])
        print data
        socket.sendto(data.upper(), self.client_address)

if __name__ == '__main__':

     HOST, PORT = "localhost", 9994
     server = SocketServer.UDPServer((HOST, PORT), MyUDPHandler)
     server.serve_forever()
