### ISSUE TITLE
How to use ProtoBuf in Cocos2d-jsb?

### ISSUE THREAD

**Issue by zxh1982** [protobufjs/protobuf.js#57]
I use ProtoBuf(require files: ByteBuffer.min.js, Long.min.js, ProtoBuf.min.js) in cocos2d-jsb, and require ByteBuffer.min.js error, need other files( buffer, process).

please help me, how to use ProtoBuf in Cocos2d-jsb

**Comment by assslove** [comment]
@tiantian20007  how do you get it work? cocos2d-js protobuf.js
