### ISSUE TITLE
Type Script compatibility issue.

### ISSUE THREAD

**Issue by Arun-KumarH** [protobufjs/protobuf.js#838]
protobuf.js version: 6.8.0

pbjs and pbts cli versions are v6.6.5.
I have used the pbjs and pbts cli to generate static code and type defintions for my proto files.

pbjs -t static-module -w commonjs -o bundled.js
pbts -o bundled.d.ts bundled.js

With protobufjs version 6.7 I did not face any issues but with 6.8 release last week I am getting below error.

```
definitions/bundled.d.ts(219,72): error TS2694: Namespace '"/chassis-srv/node_modules/protobufjs/index"' has no exported member 'ConversionOptions'.
```

**Comment by mhgamework** [comment]
I have the same problem

**Comment by mlamp** [comment]
Found a solution, first generate your static bundled.js and bundled.d.ts from that js, then compile your server code (ofc, update npm packages as well).

**Comment by dcodeIO** [comment]
There have been a couple of [changes](https://github.com/dcodeIO/protobuf.js/blob/master/CHANGELOG.md) between versions making it necessary to recompile static code.
