### ISSUE TITLE
Map fields with empty string as key are handled incorrectly

### ISSUE THREAD

**Issue by mkosieradzki** [protobufjs/protobuf.js#843]
protobuf.js version: 6.8.0

UPDATED:
Current codegen for map-fields when string key is empty is incorrect.

ORIGINAL:
Current codegen for map-fields is invalid. It assumes that map keys are non empty (!) strings (!!).

1. Map CAN have empty string as indices.
2. ~~Map CAN be indexed by something different than string...~~

~~Both parsing and JS representation (Object instead of Map) are broken.~~

**Comment by dcodeIO** [comment]
It does not assume that protobuf map keys are strings, it just makes any map keys string on the JS-side because that's how it works in JavaScript. For example, long ints are converted to an 8-bit hash string and there are utility functions to convert / generate these keys.

**Comment by mkosieradzki** [comment]
@dcodeIO Thanks, I have jumped to conclusion. So only empty string are mishandled.

**Comment by mkosieradzki** [comment]
I have fixed the codegen in my fork and I will create a PR soon.
