### ISSUE TITLE
Using --no-comments in pbjs results in (almost) empty d.ts file

### ISSUE THREAD

**Issue by Lopdo** [protobufjs/protobuf.js#846]
protobuf.js version: 6.8.0

I am using follwing script:
```
pbjs -t static-module -w es6  --force-message --no-convert --no-create --no-delimited --no-verify  --no-comments -o some_path/file.js
pbts -o some_path/file.d.ts some_path/file.js
```

JS file is generated correctly, but output of pbts is file with just one line:
```js
import * as $protobuf from "protobufjs";
```

when I remove --no-comments from pbjs command, resulting d.ts file contains everything it should

**Comment by vaiwa** [comment]
Failing in version 6.6.5 too

**Comment by dcodeIO** [comment]
Generation of type definitions is performed from jsdoc comments ([see](https://github.com/dcodeIO/protobuf.js/tree/master/cli/lib/tsd-jsdoc)).

**Comment by vaiwa** [comment]
This should be imho mentioned in the documentation
