### ISSUE TITLE
handle 'type.googleapis.com/' string

### ISSUE THREAD

**Issue by FoghostCn** [protobufjs/protobuf.js#850]
protobuf.js version: 6.8.0

in google's any.proto file I find this document:

> The pack methods provided by protobuf library will by default use
 'type.googleapis.com/full.type.name' as the type URL and the unpack
 methods only use the fully qualified type name after the last '/'
 in the type URL, for example "foo.bar.com/x/y.z" will yield type
 name "y.z".

and I have seen your code about `any` type
```js
wrappers[".google.protobuf.Any"] = {
    fromObject: function(object) {
        // unwrap value type if mapped
        if (object && object["@type"]) {
            var type = this.lookup(object["@type"]);
            ........
        }
        return this.fromObject(object);
    },
    toObject: function(message, options) {
        // decode value if requested and unmapped
        if (options && options.json && message.type_url && message.value) {
            var type = this.lookup(message.type_url);
        .......
        return this.toObject(message, options);
    }
};
```
`fromObject` and `toObject` method didn't handle `type.googleapis.com/` string 

actually `Msg.decode(buffer).toJSON()` didn't auto decode `Any` type with `type_url =type.googleapis.com/myMsg` but can auto decode `.myMsg`

did I missing something?

**Comment by dobryanskyy** [comment]
Hi @FoghostCn , did you manage to find out how to make this working?

**Comment by FoghostCn** [comment]
@dobryanskyy I have to override the two method `fromObject` and `toObject` with this
```js
protobufjs.wrappers['.google.protobuf.Any'] = {
    fromObject(object) {
        if (object && object["@type"]) {
            const t = object["@type"];
            const type = this.lookup(t);
            if (type) {
                return this.create({
                    type_url: `type.googleapis.com/${t}`,
                    value: type.encode(type.fromObject(object)).finish()
                });
            }
        }
        return this.fromObject(object);
    },
    toObject(message, options) {
        if (options && options.json && message.type_url && message.value) {
            const type = this.lookup(message.type_url.replace('type.googleapis.com/', ''));
            if (type) {
                message = type.decode(message.value);
            }
        }
        if (!(message instanceof this.ctor) && message instanceof protobufjs.Message) {
            const object = message.$type.toObject(message, options);
            const name = message.$type.fullName;
            object["@type"] = name.charAt(0) === '.' ? name.substr(1) : name;
            return object;
        }
        return this.toObject(message, options);
    }
};
```

**Comment by dobryanskyy** [comment]
great, thanks

**Comment by nickpestov** [comment]
@dcodeIO, are there any plans to add the `type.googleapis.com/` prefix to `@type`?
Currently, if we follow Google's Any.proto docs and include the prefix, `fromObject` fails to lookup the type and `toObject` sets an `@type` that is not compatible with what other clients expect.
Would submitting the above as a PR help progress this?

**Comment by johncsnyder** [comment]
+1 I'm also running into this issue. Ive tested out the PR https://github.com/protobufjs/protobuf.js/pull/1068 locally and its working great.
