### ISSUE TITLE
Load .pbtxt files using protobuf.js

### ISSUE THREAD

**Issue by lutzroeder** [protobufjs/protobuf.js#957]

**Comment by dcodeIO** [comment]
There is no support for data in text format, yet. Would make a nice [extension](https://github.com/dcodeIO/protobuf.js/tree/master/ext), though.

**Comment by sk-** [comment]
@lutzroeder any chance on sharing a beta version of your changes. If you share some instructions on how to use it, I could give it a try and report back with any issues.

**Comment by lutzroeder** [comment]
@sk- Have a look at [package.json](https://github.com/lutzroeder/netron/blob/master/package.json) and #1270 and #1112. It would be helpful if you can get some feedback from maintainers what would be needed to get this merged.

**Comment by sk-** [comment]
Thanks @lutzroeder I tested it and works, although when using typescript there are some problems as some of the types are not exported.

This is the error I'm getting:
`error TS2694: Namespace '"node_modules/protobufjs/index"' has no exported member 'TextReaders'`

**Comment by lutzroeder** [comment]
@sk- can you submit a fix? @dcodeIO mentioned keeping this modular is desirable. As mentioned earlier not sure the issue here is more bug reports that complicate integration. If maintainers dropped the ball on this project due to other priorities or aren't working towards integrating the PR this might be a dead end and code needs to move in an entirely different direction. What is missing is feedback from someone that would be able to merge the change on what needs to be done next.
