### ISSUE TITLE
Decode enums to their string values

### ISSUE THREAD

**Issue by kurtraschke** [protobufjs/protobuf.js#97]
It would be nice if there were an easy way (as a global flag, or a builder option?) to get enums decoded to their string values rather than the corresponding integer constants.

**Comment by zhiqingchen** [comment]
+1
no easy,
should enums decoded to their string values by default?

**Comment by jonywtf** [comment]
+1
I need enums string values by default, too!
https://github.com/grpc/grpc/issues/1019

**Comment by zhiqingchen** [comment]
Temporary Solution https://github.com/zhiqingchen/ProtoBuf.js/commit/9a164b8a21d35929f13bedb82294dc9a2f1f362a

**Comment by meszarv** [comment]
+1
It would be nice to have this feature built in. Maybe as an additional option in decode method...

**Comment by othree** [comment]
Should work for current release. https://gist.github.com/othree/dc254e34056f86fa069e

**Comment by tvdstaaij** [comment]
My solution using pure reflection (i.e. no modifications to ProtoBuf.js itself) and [lodash](https://github.com/lodash/lodash):

https://gist.github.com/tvdstaaij/044b3f4fdbe6ffcf6bec

Seems to work in my use case but not sure how robust it is. Improvements are welcome.

**Comment by michaelhogg** [comment]
[`ProtoBuf.Builder.Message.toRaw()`](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L540) seems to work.

It calls [`cloneRaw()`](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L486) which ["converts enum values to their respective names"](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L488-L493).

Simply call `.toRaw()` on the `ProtoBuf.Builder.Message` returned by [`decode()`](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L573).

**Comment by menocomp** [comment]
Just use this as option while imporing the proto in the client: `enums: String`
